---
- name: reload modsecurity nginx
  command: docker exec {{ modsecurity_nginx_name }} nginx -s reload
  when: ansible_env.MOLECULE_SCENARIO_NAME is not defined
  failed_when: false

- name: restart modsecurity nginx
  community.docker.docker_compose_v2:
    project_src: "/etc/modsecurity-nginx"
    recreate: always
  when: ansible_env.MOLECULE_SCENARIO_NAME is not defined
  failed_when: false
