- name: Stop all Docker Compose services on source server (/var/www)
  ansible.builtin.shell: |
    cd /var/www/{{ item }} && docker-compose down
  loop: '{{ docker_services_www }}'
  when: "'source' in group_names"

- name: Stop all Docker Compose services on source server (/opt)
  ansible.builtin.shell: |
    cd /opt/{{ item }} && docker-compose down
  loop: '{{ docker_services_opt }}'
  when: "'source' in group_names"

- name: Stop all Docker Compose services on source server (/home/{{ ansible_user }})
  ansible.builtin.shell: |
    cd /home/{{ ansible_user }}/{{ item }} && docker-compose down
  loop: '{{ docker_services_home }}'
  when: "'source' in group_names"

- name: Create backup of Docker Compose services on source server (/var/www)
  ansible.builtin.shell: |
    cd /var/www/{{ item }} && tar -czvf /home/{{ ansible_user }}/{{ item }}-backup-{{ ansible_date_time.date }}.tar.gz .
  loop: '{{ docker_services_www }}'
  when: "'source' in group_names"

- name: Create backup of Docker Compose services on source server (/opt)
  ansible.builtin.shell: |
    cd /opt/{{ item }} && tar -czvf /home/{{ ansible_user }}/{{ item }}-backup-{{ ansible_date_time.date }}.tar.gz .
  loop: '{{ docker_services_opt }}'
  when: "'source' in group_names"

- name: Create backup of Docker Compose services on source server (/home/{{ ansible_user }})
  ansible.builtin.shell: |
    cd /home/{{ ansible_user }}/{{ item }} && tar -czvf /home/{{ ansible_user }}/{{ item }}-backup-{{ ansible_date_time.date }}.tar.gz .
  loop: '{{ docker_services_home }}'
  when: "'source' in group_names"

- name: Transfer backup files to destination server (/var/www)
  ansible.builtin.copy:
    src: '/home/{{ ansible_user }}/{{ item }}-backup-{{ ansible_date_time.date }}.tar.gz'
    dest: '{{ backup_dir }}'
  delegate_to: destination
  loop: '{{ docker_services_www }}'
  when: "'source' in group_names"

- name: Transfer backup files to destination server (/opt)
  ansible.builtin.copy:
    src: '/home/{{ ansible_user }}/{{ item }}-backup-{{ ansible_date_time.date }}.tar.gz'
    dest: '{{ backup_dir }}'
  delegate_to: destination
  loop: '{{ docker_services_opt }}'
  when: "'source' in group_names"

- name: Transfer backup files to destination server (/home/{{ ansible_user }})
  ansible.builtin.copy:
    src: '/home/{{ ansible_user }}/{{ item }}-backup-{{ ansible_date_time.date }}.tar.gz'
    dest: '{{ backup_dir }}'
  delegate_to: destination
  loop: '{{ docker_services_home }}'
  when: "'source' in group_names"