#ENC[AES256_GCM,data:Gl9OX5uLjB00ygZc9jLZDLo=,iv:5ZBKijp1pj4KPrRwqMUCB31lnZjUhBPbOa9UrszfbPE=,tag:OWw+vcmJ61SxbNE/wdF6rA==,type:comment]
openclaw:
    gateway_token: ENC[AES256_GCM,data:I1T3LLD7dJw5raglFueOTqGdpRePl3y5OblAd1lyzcHZTTgjS091J1CuTrI=,iv:O0hG/jUwx1tfxVABQ8eHbpddyYHC1gQjUf3l2UE2wKc=,tag:V46rp0ZWCOUskGCk0JQQ1g==,type:str]
    kimi_api_key: ENC[AES256_GCM,data:WKnv1nmVjYlpbnhClt7SsdCV6ELtQ1TM6vHDVY2MswFDXM6XD5SFM1Ti59FZyj6ut84eXK8KBskgL7ARigg1H+Svg6onYR2m,iv:O/hcLFGsFab/sBMZy3qtAOBr876fWi+9s2pviP+RhSo=,tag:43eDwNZu47p283scTltFAw==,type:str]
    discord_webhook_url: ENC[AES256_GCM,data:CBEr156dXtzJRQ5Epsu4dCWStPC8gxsKg6z5QLkiuliGKovSXK6R6lPGCB8kv1WGSVAhUypOXlXl1Oz34zlRvbi6Mb74OLK+7k34so37qWibuHVoCbQNt7GKtrqRhFcczuFSxX8PQ9rRkThHpzDGBJDiU2dHyMoaIw==,iv:tAhG1VwSHGV8UsSWwO+9eH7jh9KVoxiO+edpq3T0SA0=,tag:Gknpzh2d+Rgh6mLh6qdEKw==,type:str]
    discord_bot_token: ENC[AES256_GCM,data:ZtdKelENghsphmN060/1G8Emv0Wm240efir1WJxKUVBtDD6gJg3nP2P0zg3/qMdy4tyRVkEJpz8St78YNxtTavMDAC9SbC91,iv:FULcvyv75NQR/71pXLKoKHGr4FQ1PciCC8l2xJxRaSM=,tag:mtXWLhY1yZnD0J+x2pFgeQ==,type:str]
    discord_guild_id: ENC[AES256_GCM,data:YPCf9jOkLqpYsRmNQDre7Z445Q==,iv:f9wy8DLCL2mZx/0VxydRnkf9l85HiVZjoVbc9P3OzSM=,tag:fQewNs6juZilFNSG+Fh9DA==,type:str]
    discord_admin_user_id: ENC[AES256_GCM,data:7Obez7QxSSgHfWbasr6GK8uT,iv:fUzg5r1V2iJi6tQ9cDX4NogflttGQ5AnH80luyEx1hc=,tag:ymN4QlvvGIXPnfqzLaPN1A==,type:str]
    matrix_password: ENC[AES256_GCM,data:ud7COmWIDAR6HVbfQnoKpeeIdUSx1mo0cFIYZNQJfPA2ekzQ0Lh1jtBgqaZkS9POnw7VmI4WmV0AG15qfuJnM9SmFbFxdv/sURkQhROnfywLCIEfeUQu4rGq0HnMt19MIDvcSXeM/a//ZHsYPLkTHo+LGYqo5Hd2ydFwMEnyYK4=,iv:uMCrK+moGEyFmI+tBEimDj/sdQ4IU+ukV7qWOD+xcTo=,tag:7q9xQpu03rdhFVi4d9P5Kg==,type:str]
sops:
    age:
        - recipient: age1paqwux2ffqspe3ltux45wvn2vzdy24hwj8utgt0en64afeys4vuqxjpcvl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5bnRtL0RrV2phSnR3NC9Q
            TWt1cEhrUEg5cWQ1OGkwTGR6SkJ2d2ptTHcwCnNYaGp6Y2xiVXpGbkNwTGNPNnNR
            ZjJvSkMzQlA5cnBRN3VLQ29jME02S3cKLS0tIHB6OWZxWW5oZUtobHFxODVRSDhj
            em9aNEIvT0x0VWIzNUhoNXh6WFhGaDgKuFBNUS1Zd2dGVQr5SKGe5mmOMo3jDKVh
            WcHvtY8VZVcZz4vI2a8g9rttP6+WdoxnqcQ6oKD7CLB02PPvGyEJcw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-13T06:28:30Z"
    mac: ENC[AES256_GCM,data:vgs1Zjfpl9Z2HQaZV5T5ssaq0IjDW2ULIj2hVIfG6471OCcAcRMipuvgTT+IZatCwuInRwgHRP75MXctJVbxBySqhmnhQE6iejDNasnzAxOJE3NK6IVH5yqI+VtuE7tEWuYoyt8XV3V6/jpf9tZr7BHYVjftJ7F36OKAR6XA7tA=,iv:BYH4KuJkum2e1DXWmyu/dZM2V2+839Uu0nsXrzfv+KM=,tag:ssAjiTUED3fpcPtnvc7cgg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
