#ENC[AES256_GCM,data:Gl9OX5uLjB00ygZc9jLZDLo=,iv:5ZBKijp1pj4KPrRwqMUCB31lnZjUhBPbOa9UrszfbPE=,tag:OWw+vcmJ61SxbNE/wdF6rA==,type:comment]
openclaw:
    gateway_token: ENC[AES256_GCM,data:I1T3LLD7dJw5raglFueOTqGdpRePl3y5OblAd1lyzcHZTTgjS091J1CuTrI=,iv:O0hG/jUwx1tfxVABQ8eHbpddyYHC1gQjUf3l2UE2wKc=,tag:V46rp0ZWCOUskGCk0JQQ1g==,type:str]
    kimi_api_key: ENC[AES256_GCM,data:gdKaHdkhDIuUm16llsv0JAyNk14PULTYg7U1eigdkAtmIGdGPu+L5HeiEvqLV1TSidUj9k+9g/6li3fX/IxbUT/GT9KK5jHJ,iv:wdhArQWH98GdzCRSbwHqKmUlcbf0dXzohu+JwaVWrWk=,tag:K03d+WpowdqX0vubjLK/cw==,type:str]
sops:
    age:
        - recipient: age1paqwux2ffqspe3ltux45wvn2vzdy24hwj8utgt0en64afeys4vuqxjpcvl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5bnRtL0RrV2phSnR3NC9Q
            TWt1cEhrUEg5cWQ1OGkwTGR6SkJ2d2ptTHcwCnNYaGp6Y2xiVXpGbkNwTGNPNnNR
            ZjJvSkMzQlA5cnBRN3VLQ29jME02S3cKLS0tIHB6OWZxWW5oZUtobHFxODVRSDhj
            em9aNEIvT0x0VWIzNUhoNXh6WFhGaDgKuFBNUS1Zd2dGVQr5SKGe5mmOMo3jDKVh
            WcHvtY8VZVcZz4vI2a8g9rttP6+WdoxnqcQ6oKD7CLB02PPvGyEJcw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-13T02:03:48Z"
    mac: ENC[AES256_GCM,data:hcL2c6yGwq6JMhCPBSSaV3MfEAlquANpsHEcZUrKj1N7UEjZiiDy4ZFhnKCAQx2RRSNQ3eK5HiVeJz+WpOaIK2Ava1Jx6SPlnC4Z/vRpNyB7B0QwJCRV9Hr0t3NlvtVPmdPbM/4wBRF1GvvrL7L0Ygp+GyLszwE2fyUxVGt2dp4=,iv:OMeKoTfXcm83obw/yT/irs9sebJS+kspMAJeHsgNuMQ=,tag:bRuCDdltfuCQYwp2swPllg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
