- name: Check if yami branch exists
  command: git branch --list yami
  args:
    chdir: '{{ ctfd_dir }}'
  register: yami_branch_exists
  ignore_errors: yes

- name: Create yami branch if it doesn't exist
  command: git checkout -b yami origin/yami
  args:
    chdir: '{{ ctfd_dir }}'
  when: yami_branch_exists.stdout == ""

- name: Checkout to yami branch
  command: git checkout yami
  args:
    chdir: '{{ ctfd_dir }}'

- name: Pull latest changes from yami branch
  command: git pull origin yami
  args:
    chdir: '{{ ctfd_dir }}'

- name: Check if CTFd Docker container is running
  shell: docker ps --filter "name=ctfd_ctfd_1" --format "{{'{{'}}.Names{{'}}'}}"
  register: ctfd_container_status
  ignore_errors: yes

- name: Start or restart CTFd Docker container
  block:
    - name: Restart existing CTFd Docker container
      community.docker.docker_compose_v2:
        project_src: '{{ ctfd_dir }}'
        restarted: true
      when: ctfd_container_status.stdout is defined and ctfd_container_status.stdout != ""

    - name: Start new CTFd Docker container
      community.docker.docker_compose_v2:
        project_src: '{{ ctfd_dir }}'
        state: present
        restarted: true
      when: ctfd_container_status.stdout is not defined or ctfd_container_status.stdout == ""