---
- name: Check if CTFd Docker container is running
  shell: docker ps --filter "name=ctfd_ctfd_1" --format "{{.Names}}"
  register: ctfd_container_status
  ignore_errors: yes

- name: Start or restart CTFd Docker container
  block:
    - name: Restart existing CTFd Docker container
      docker_compose:
        project_src: "/home/taka/ctfd/"
        restarted: true
      when: ctfd_container_status.stdout != ""
    
    - name: Start new CTFd Docker container
      docker_compose:
        project_src: "/home/taka/ctfd/"
        state: present
        restarted: true
      when: ctfd_container_status.stdout == ""

- name: Copy CTFd Nginx configuration to /etc/nginx/conf.d/
  copy:
    src: ~/yamisskey-provision/nginx/ctfd.conf
    dest: /etc/nginx/conf.d/ctfd.conf
    owner: root
    group: root
    mode: '0644'
  notify:
    - Reload Nginx

- name: Test Nginx configuration
  command: nginx -t
  register: nginx_test_result
  failed_when: nginx_test_result.rc != 0

- name: Restart Nginx to apply changes
  systemd:
    name: nginx
    state: restarted
    enabled: true
  when: nginx_test_result.rc == 0

- name: Reload Nginx
  systemd:
    name: nginx
    state: reloaded
  when: nginx_test_result.rc == 0