---
- name: Create backup base directory
  file:
    path: "{{ backup_dir }}/misskey"
    state: directory
    owner: '{{ ansible_user }}'
    group: '{{ ansible_user }}'
    mode: '0755'

- name: Clone misskey-backup repository
  git:
    repo: "{{ misskey_backup_repo }}"
    dest: "{{ misskey_backup_dir }}"
    version: "{{ misskey_backup_version }}"
    force: true
  when: ansible_env.MOLECULE_SCENARIO_NAME is not defined

- name: Create backups directory
  file:
    path: "{{ misskey_backup_dir }}/backups"
    state: directory
    owner: '{{ ansible_user }}'
    group: '{{ ansible_user }}'
    mode: '0755'

- name: Create backup environment file
  template:
    src: env.j2
    dest: "{{ misskey_backup_dir }}/.env"
    mode: '0600'
  notify: Restart backup container
  when:
    - misskey_backup_r2_access_key_id is defined
    - misskey_backup_b2_account is defined
    - ansible_env.MOLECULE_SCENARIO_NAME is not defined

- name: Build and start backup container
  community.docker.docker_compose_v2:
    project_src: "{{ misskey_backup_dir }}"
    build: always
    pull: always
  register: compose_result
  when: ansible_env.MOLECULE_SCENARIO_NAME is not defined
