---
- name: Check if directory exists
  ansible.builtin.stat:
    path: '{{ misskey_dir }}'
  register: dir_check

- name: Ensure Misskey directory exists
  file:
    path: '{{ misskey_dir }}'
    state: directory
    owner: "{{ ansible_user | default('root') }}"
    group: "{{ ansible_user | default('root') }}"
    mode: '0755'

- name: Create required directories
  file:
    path: '{{ item }}'
    state: directory
    mode: '0755'
  loop:
    - '{{ misskey_dir }}/.config'
    - '{{ misskey_dir }}/files'
    - '{{ misskey_dir }}/redis'
    - '{{ misskey_dir }}/db'

- name: Check if required files exist
  ansible.builtin.stat:
    path: '{{ item }}'
  loop:
    - '{{ misskey_dir }}/docker-compose.yml'
    - '{{ misskey_dir }}/.config/default.yml'
    - '{{ misskey_dir }}/.config/docker.env'
  register: required_files

- name: Deploy docker-compose.yml
  template:
    src: misskey_docker-compose.yml.j2
    dest: '{{ misskey_dir }}/docker-compose.yml'
    mode: '0644'
  when: not required_files.results[0].stat.exists

- name: Deploy default.yml from template
  template:
    src: docker_example.yml.j2
    dest: '{{ misskey_dir }}/.config/default.yml'
    mode: '0644'
  when: not required_files.results[1].stat.exists

- name: Deploy docker.env from template
  template:
    src: docker_example.env.j2
    dest: '{{ misskey_dir }}/.config/docker.env'
    mode: '0644'
  when: not required_files.results[2].stat.exists

- name: Recheck if required files exist
  ansible.builtin.stat:
    path: '{{ item }}'
  loop:
    - '{{ misskey_dir }}/docker-compose.yml'
    - '{{ misskey_dir }}/.config/default.yml'
    - '{{ misskey_dir }}/.config/docker.env'
  register: final_check

- name: Fail if required files are still missing
  fail:
    msg: 'Required file {{ item.item }} not found'
  when:
    - not item.stat.exists
    - not ansible_check_mode
  loop: '{{ final_check.results }}'

- name: Deploy postgresql.conf
  template:
    src: misskey_postgresql.conf.j2
    dest: '{{ misskey_dir }}/.config/postgresql.conf'
    mode: '0644'

- name: Check if database is initialized
  ansible.builtin.stat:
    path: '{{ misskey_dir }}/db/PG_VERSION'
  register: db_initialized

- name: Stop existing containers before first initialization
  command: '{{ docker_compose_cmd }} down'
  args:
    chdir: '{{ misskey_dir }}'
  when:
    - not db_initialized.stat.exists
    - not ansible_check_mode

- name: Initialize database (first time only)
  command: '{{ docker_compose_cmd }} run --rm web pnpm run init'
  args:
    chdir: '{{ misskey_dir }}'
  when:
    - not db_initialized.stat.exists
    - not ansible_check_mode
  register: init_output
  failed_when: init_output.rc != 0

- name: Determine if updates are needed
  set_fact:
    updates_needed: "{{ (git_pull_output.stdout | default('Already up to date.')) != 'Already up to date.' or (git_submodule_update_output.stdout | default('')) != '' }}"

- name: Stop Misskey services
  command: '{{ docker_compose_cmd }} stop'
  args:
    chdir: '{{ misskey_dir }}'
  when:
    - updates_needed or not db_initialized.stat.exists
    - not ansible_check_mode

- name: Start Misskey
  command: '{{ docker_compose_cmd }} up -d'
  args:
    chdir: '{{ misskey_dir }}'
  when: not ansible_check_mode
  register: start_output
  failed_when: start_output.rc != 0

- name: Change permissions of files directory
  file:
    path: '{{ misskey_dir }}/files'
    state: directory
    mode: '0777'
  when: not ansible_check_mode

- name: Ensure backup directory exists
  file:
    path: '{{ backup_dir }}/misskey'
    state: directory
    owner: '{{ ansible_user }}'
    group: '{{ ansible_user }}'
    mode: '0755'
  when: not ansible_check_mode

- name: Check if VAPID keys file exists
  ansible.builtin.stat:
    path: '{{ backup_dir }}/misskey/vapid_keys.yml'
  register: vapid_keys_file
  when: not ansible_check_mode

- name: Generate VAPID keys
  command: docker run node npx web-push generate-vapid-keys --json
  register: vapid_keys
  when:
    - not ansible_check_mode
    - not (vapid_keys_file.stat.exists | default(true))

- name: Save VAPID keys to a file
  ansible.builtin.copy:
    content: '{{ vapid_keys.stdout }}'
    dest: '{{ backup_dir }}/misskey/vapid_keys.yml'
  when:
    - not ansible_check_mode
    - not (vapid_keys_file.stat.exists | default(true))

- name: Load VAPID keys from file
  ansible.builtin.slurp:
    src: '{{ backup_dir }}/misskey/vapid_keys.yml'
  register: vapid_keys_content
  when: not ansible_check_mode

- name: Debug VAPID keys content
  debug:
    var: vapid_keys_content.content
  when: not ansible_check_mode

- name: Decode VAPID keys data
  set_fact:
    vapid_keys_data: "{{ vapid_keys_content.content | b64decode | from_yaml }}"
  when: not ansible_check_mode

- name: Set VAPID keys variables
  set_fact:
    vapid_public_key: "{{ vapid_keys_data.publicKey }}"
    vapid_private_key: "{{ vapid_keys_data.privateKey }}"
  when: not ansible_check_mode

- name: Print VAPID keys
  debug:
    msg:
      - 'Public Key: {{ vapid_public_key }}'
      - 'Private Key: {{ vapid_private_key }}'
  when: not ansible_check_mode
