---
# 1. ディレクトリ構造の作成
- name: Create directory structure
  file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
    owner: "4001"
    group: "4001"
  with_items:
    - "{{ cryptpad_dir }}/config"
    - "{{ cryptpad_dir }}/data/blob"
    - "{{ cryptpad_dir }}/data/block"
    - "{{ cryptpad_dir }}/data/data"
    - "{{ cryptpad_dir }}/data/files"
    - "{{ cryptpad_dir }}/customize"
    - "{{ cryptpad_dir }}/onlyoffice-dist"
    - "{{ cryptpad_dir }}/onlyoffice-conf"

# 2. シークレット関連のタスク
- name: Check if secrets file exists
  stat:
    path: "{{ cryptpad_secrets_file }}"
  register: cryptpad_secrets_file_stat

- name: Generate secret key if not exists
  shell: 'cat /dev/urandom | tr -dc A-Za-z0-9 | head -c 64'
  register: secret_key_output
  when: not cryptpad_secrets_file_stat.stat.exists

- name: Set secret key fact
  set_fact:
    cryptpad_secret_key: "{{ (lookup('file', cryptpad_secrets_file) | from_yaml).secret_key if cryptpad_secrets_file_stat.stat.exists else secret_key_output.stdout }}"

- name: Save secrets to file
  copy:
    dest: "{{ cryptpad_secrets_file }}"
    content: |
      secret_key: "{{ cryptpad_secret_key }}"
  when: not cryptpad_secrets_file_stat.stat.exists

# 3. 設定ファイルの作成
- name: Create and set permissions for config.js
  template:
    src: cryptpad_config.j2
    dest: "{{ cryptpad_dir }}/config/config.js"
    mode: '0644'
    owner: "4001"
    group: "4001"
  notify: restart cryptpad

# 4. Docker関連の設定
- name: Copy docker-compose configuration
  template:
    src: cryptpad_docker-compose.yml.j2
    dest: "{{ cryptpad_dir }}/docker-compose.yml"
    mode: '0644'
    owner: root
    group: root
  notify: restart cryptpad

- name: Copy nginx configuration
  template:
    src: nginx_cryptpad.conf.j2
    dest: /etc/nginx/conf.d/cryptpad.conf
    mode: '0644'
  notify:
    - check nginx configuration
    - reload nginx

# 5. コンテナの管理
- name: Pull CryptPad Docker image
  docker_image:
    name: cryptpad/cryptpad
    tag: version-2024.9.1
    source: pull
    force_source: yes

- name: Start CryptPad containers
  docker_compose:
    project_src: "{{ cryptpad_dir }}"
    state: present
    restarted: yes