---
- name: Install git for cloning repository
  apt:
    name: git
    state: present
  become: true

- name: Create required directories
  file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
    owner: "4001"
    group: "4001"
  with_items:
    - "{{ cryptpad_dir }}"
    - "{{ cryptpad_dir }}/data/blob"
    - "{{ cryptpad_dir }}/data/block"
    - "{{ cryptpad_dir }}/data/data"
    - "{{ cryptpad_dir }}/data/files"
    - "{{ cryptpad_dir }}/customize"
    - "{{ cryptpad_dir }}/config"
    - "{{ cryptpad_dir }}/onlyoffice-dist"
    - "{{ cryptpad_dir }}/onlyoffice-conf"
    - "{{ cryptpad_dir }}/src"

- name: Clone CryptPad repository
  git:
    repo: https://github.com/cryptpad/cryptpad.git
    dest: "{{ cryptpad_dir }}/src"
    version: main
  register: git_clone

- name: Copy Dockerfile and related files
  copy:
    src: "{{ cryptpad_dir }}/src/{{ item }}"
    dest: "{{ cryptpad_dir }}/{{ item }}"
    remote_src: yes
  with_items:
    - Dockerfile
    - .dockerignore
    - docker-entrypoint.sh
  when: git_clone.changed

- name: Build CryptPad Docker image
  docker_image:
    name: cryptpad/cryptpad
    tag: local-latest
    build:
      path: "{{ cryptpad_dir }}"
      pull: yes
    source: build
  notify: restart cryptpad

- name: Check if secrets file exists
  stat:
    path: "{{ cryptpad_secrets_file }}"
  register: cryptpad_secrets_file_stat

- name: Generate secret key if not exists
  shell: 'cat /dev/urandom | tr -dc A-Za-z0-9 | head -c 64'
  register: secret_key_output
  when: not cryptpad_secrets_file_stat.stat.exists

- name: Set secret key fact
  set_fact:
    cryptpad_secret_key: "{{ (lookup('file', cryptpad_secrets_file) | from_yaml).secret_key if cryptpad_secrets_file_stat.stat.exists else secret_key_output.stdout }}"

- name: Save secrets to file
  copy:
    dest: "{{ cryptpad_secrets_file }}"
    content: |
      secret_key: "{{ cryptpad_secret_key }}"
  when: not cryptpad_secrets_file_stat.stat.exists
  notify: restart cryptpad

- name: Update docker-compose template for local image
  template:
    src: cryptpad_docker-compose.yml.j2
    dest: "{{ cryptpad_dir }}/docker-compose.yml"
    mode: '0644'
    owner: root
    group: root
  vars:
    cryptpad_image: "cryptpad/cryptpad:local-latest"
  notify: restart cryptpad

- name: Copy CryptPad configuration
  template:
    src: cryptpad_config.j2
    dest: "{{ cryptpad_dir }}/config/config.js"
    mode: '0644'
    owner: "4001"
    group: "4001"
  notify: restart cryptpad

- name: Copy nginx configuration
  template:
    src: nginx_cryptpad.conf.j2
    dest: /etc/nginx/conf.d/cryptpad.conf
    mode: '0644'
  notify:
    - check nginx configuration
    - reload nginx

- name: Set correct permissions for CryptPad directories
  file:
    path: "{{ item }}"
    owner: "4001"
    group: "4001"
    recurse: yes
  with_items:
    - "{{ cryptpad_dir }}/data"
    - "{{ cryptpad_dir }}/customize"
    - "{{ cryptpad_dir }}/onlyoffice-dist"
    - "{{ cryptpad_dir }}/onlyoffice-conf"

- name: Start CryptPad containers
  docker_compose:
    project_src: "{{ cryptpad_dir }}"
    state: present
    restarted: yes