---
# ModSecurity CRS NGINX default variables

# Container configuration
modsecurity_nginx_name: "modsecurity-nginx"
modsecurity_nginx_image: "owasp/modsecurity-crs"
modsecurity_nginx_tag: "nginx"
modsecurity_nginx_restart_policy: "unless-stopped"

# Network configuration
modsecurity_nginx_port: "8080"
modsecurity_nginx_ssl_port: "8443"
modsecurity_nginx_host_port: "80"
modsecurity_nginx_host_ssl_port: "443"

# Backend configuration
modsecurity_backend: "http://127.0.0.1:3000"
modsecurity_server_name: "localhost"

# ModSecurity configuration
modsecurity_rule_engine: "On"
modsecurity_req_body_access: "On"
modsecurity_resp_body_access: "On"
modsecurity_audit_engine: "RelevantOnly"
modsecurity_audit_log_format: "JSON"
modsecurity_log_level: "warn"

# CRS configuration
modsecurity_blocking_paranoia: 2
modsecurity_detection_paranoia: 2
modsecurity_anomaly_inbound: 5
modsecurity_anomaly_outbound: 4
modsecurity_allowed_methods: "GET HEAD POST OPTIONS PUT PATCH DELETE"
modsecurity_allowed_request_content_type: |
  application/x-www-form-urlencoded|
  multipart/form-data|
  multipart/related|
  text/xml|
  application/xml|
  application/soap+xml|
  application/json|
  application/cloudevents+json|
  application/cloudevents-batch+json
modsecurity_allowed_http_versions: "HTTP/1.0 HTTP/1.1 HTTP/2 HTTP/2.0"

# SSL/TLS configuration
modsecurity_ssl_protocols: "TLSv1.2 TLSv1.3"
modsecurity_always_tls_redirect: "off"

# Logging
modsecurity_access_log: "/var/log/nginx/access.log"
modsecurity_error_log: "/var/log/nginx/error.log"

# Custom rules
modsecurity_custom_rules_before: []
modsecurity_custom_rules_after: []

# Docker volumes
modsecurity_docker_volumes:
  - "/var/log/nginx:/var/log/nginx"
  - "/etc/ssl/certs:/etc/ssl/certs:ro"
