- name: Update and upgrade apt packages
  apt:
    update_cache: yes
    upgrade: 'dist'
  tags:
    - update

- name: Install essential packages
  apt:
    name: '{{ packages }}'
    state: present
  tags:
    - packages

- name: Copy unattended-upgrades configuration file
  copy:
    src: 20auto-upgrades
    dest: /etc/apt/apt.conf.d/20auto-upgrades
    owner: root
    group: root
    mode: '0644'
  tags:
    - unattended-upgrades

- name: Ensure unattended-upgrades service is enabled and started
  systemd:
    name: unattended-upgrades
    enabled: yes
    state: started
  tags:
    - unattended-upgrades

- name: Install Nix (multi-user setup)
  become: true
  become_user: "{{ user_name }}"
  shell: curl -L https://nixos.org/nix/install | sh -s -- --daemon
  args:
    creates: '/nix/store'
  tags:
    - nix_install

- name: Configure Nix to use flakes
  lineinfile:
    path: '/etc/nix/nix.conf'
    line: 'experimental-features = nix-command flakes'
    create: yes

- name: Apply Home Manager configuration
  become_user: "{{ user_name }}"
  shell: nix run home-manager -- switch --flake ".#myHome"
  environment:
    NIX_PATH: nixpkgs=https://nixos.org/channels/nixos-unstable
  tags:
    - home_manager_update