- name: Update and upgrade apt packages
  apt:
    update_cache: yes
    upgrade: 'dist'
  tags:
    - update

- name: Install essential packages
  apt:
    name: '{{ packages }}'
    state: present
  tags:
    - packages

- name: Install Nix (multi-user setup)
  become: true
  become_user: "{{ user_name }}"
  shell: curl -L https://nixos.org/nix/install | sh -s -- --daemon
  args:
    creates: '/nix/store'
  tags:
    - nix_install

- name: Configure Nix to use flakes
  lineinfile:
    path: '/etc/nix/nix.conf'
    line: 'experimental-features = nix-command flakes'
    create: yes

- name: Source Nix profile
  become: yes
  become_user: "{{ user_name }}"
  shell: |
    if [ -e /home/{{ user_name }}/.nix-profile/etc/profile.d/nix.sh ]; then
      source /home/{{ user_name }}/.nix-profile/etc/profile.d/nix.sh
    fi
    if [ -e /home/{{ user_name }}/.nix-profile/etc/profile.d/hm-session-vars.sh ]; then
      source /home/{{ user_name }}/.nix-profile/etc/profile.d/hm-session-vars.sh
    fi
  args:
    executable: /bin/bash
  ignore_errors: true

- name: Activate Home Manager
  become: yes
  become_user: "{{ user_name }}"
  shell: |
    if [ -e /home/{{ user_name }}/.nix-profile/etc/profile.d/nix.sh ]; then
      source /home/{{ user_name }}/.nix-profile/etc/profile.d/nix.sh
    fi
    if [ -e /home/{{ user_name }}/.nix-profile/etc/profile.d/hm-session-vars.sh ]; then
      source /home/{{ user_name }}/.nix-profile/etc/profile.d/hm-session-vars.sh
    fi
    nix run home-manager -- switch --flake "{{ set_dir }}#myHome"
  args:
    chdir: '{{ set_dir }}'
    executable: /bin/bash

- name: Ensure Docker is enabled and running
  systemd:
    name: docker
    enabled: yes
    state: started