- name: Update and upgrade apt packages
  apt:
    update_cache: yes
    upgrade: 'dist'
  tags:
    - update

- name: Install essential packages
  apt:
    name: '{{ packages }}'
    state: present
  tags:
    - packages

- name: Copy unattended-upgrades configuration file
  copy:
    src: 20auto-upgrades
    dest: /etc/apt/apt.conf.d/20auto-upgrades
    owner: root
    group: root
    mode: '0644'
  tags:
    - unattended-upgrades

- name: Ensure unattended-upgrades service is enabled and started
  systemd:
    name: unattended-upgrades
    enabled: yes
    state: started
  tags:
    - unattended-upgrades