ansible_user: taka
source_sudo_password: "source_user_password"
destination_sudo_password: "destination_user_password"
set_dir: '/home/{{ ansible_user }}/yamisskey-provision'
backup_script_dir: '/home/{{ ansible_user }}/misskey-backup'
mkp224o_output_dir: '/home/{{ ansible_user }}/mkp224o-output'
domain_prefix: yamiski
domain: yami.ski
github_org: yamisskey
misskey_repo: 'https://github.com/{{ github_org }}/yamisskey.git'
misskey_dir: '/var/www/misskey'
misskey_backup_secrets_file: '/opt/misskey-backup/secrets.yml'
ai_dir: '/home/{{ ansible_user }}/ai'
ctfd_dir: '/home/{{ ansible_user }}/ctfd'
synapse_server_name: matrix.{{ domain }}
synapse_secrets_file: '/var/www/synapse/secrets.yml'
element_server_name: chat.{{ domain }}
jitsi_server_name: call.{{ domain }}
matrix_use_ssl: true
minio_alias: yaminio
minio_api_server_name: drive.{{ domain }}
minio_web_server_name: minio.{{ domain }}
minio_bucket_name: "files"
minio_secrets_file: '/opt/minio/secrets.yml'
backup_dir: '/home/{{ ansible_user }}/backups'
vikunja_server_name: task.{{ domain }}
vikunja_secrets_file: '/var/www/vikunja/secrets.yml'
ctfd_server_name: ctf.{{ domain }}
grafana_server_name: grafana.{{ domain }}
searxng_repo : "https://github.com/{{ github_org }}/search.yami.ski.git"
searxng_server_name: search.{{ domain }}
searxng_dir: '/usr/local/{{ searxng_server_name }}'
searxng_env_file: '{{ searxng_dir }}/.env'
searxng_settings_file: '{{ searxng_dir }}/searxng/settings.yml'
cryptpad_server_name: pad.{{ domain }}
cryptpad_dir: '/var/www/cryptpad'
cryptpad_secrets_file: '{{ cryptpad_dir }}/secrets.yml'
growi_server_name: wiki.{{ domain }}
growi_dir: '/var/www/growi'
growi_secrets_file: '{{ growi_dir }}/secrets.yml'
uptime_server_name: uptime.{{ domain }}
uptime_dir: '/opt/uptime-kuma'
uptime_secrets_file: '{{ uptime_dir }}/secrets.yml'
deeplx_dir: '/opt/deeplx'