---
- name: Converge misskey-backup role
  hosts: all
  become: true
  gather_facts: true

  pre_tasks:
    - name: Create misskey-backup directory for skipped git clone
      file:
        path: /opt/misskey-backup
        state: directory
        mode: '0755'

  tasks:
    - name: Apply misskey-backup role
      include_role:
        name: yamisskey.servers.misskey_backup
      vars:
        ansible_user: "root"
