---
- name: Converge db_backup role
  hosts: all
  become: true
  gather_facts: true

  tasks:
    - name: Include db_backup role
      ansible.builtin.include_role:
        name: yamisskey.servers.db_backup
