- name: Reload Nginx
  become: yes
  become_user: root
  systemd:
    name: nginx
    state: reloaded

- name: Restart backup container
  docker_compose:
    project_src: /misskey-backup
    state: restarted