vaultwarden:
    admin_token: ENC[AES256_GCM,data:D7z1tZhOSDmGIgjU1ihd+kjvaMNJho0TBz4P+faEUKimu60gWUf4Vs9R5PW999ZXjfFfxwjtSKOl2+Anf+j+x/ANAun2swTd/hjzhCGfVAEnr0s2SOg1VLx9QYiQACsvUX57DOgNG+uXlF1c9gWwJ++9SU9jtw==,iv:lZX/J4X3rH58TY8XuEQ8hFVxl9T/llA3JxyAqrdjWzo=,tag:NCOzwE4QhzjZ/BLoX907LQ==,type:str]
cloudflared_tunnel_uuid: ENC[AES256_GCM,data:vLXeDv5zbzJEJ6ocBN9yu1eRcFB627WMJENShRW6ur/0RPZf,iv:81Wgd9+OAg1QB6DlCj88+GWfNbYMKeqUaFVCYKqDLu4=,tag:qwuzxtUolaBRl3sR/fNHlg==,type:str]
sops:
    age:
        - recipient: age1paqwux2ffqspe3ltux45wvn2vzdy24hwj8utgt0en64afeys4vuqxjpcvl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByRWNLZ0NqUVY0S0dJS0FS
            RSsrUkFqRk92blFaRDl3VlJTaUhGQ1RlK0VrCkV2SFgwdE94emIxNkFVQy9DR3N4
            U1dSOFE3ZmxmVlhyNFNTcWpGOXlYeUkKLS0tIE5qMnNMMnp5bUllN2k0RUQ3QUNT
            ZjNwbVNCNVZsdGxxNGVOQTFNSjFuSjAKQDoCpvf66FcYuD9eEZlj5/Rh0/Fknxkh
            lCBvYcKRz90KN5S5GonH+CzbGnlSK66MKwLDIb4mf1tUGI98HgqSag==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-02T11:41:06Z"
    mac: ENC[AES256_GCM,data:m/Y8QyPE2dN63eW9kD5xOprBwaEHiCe88fa2Sc4jWCNcvKTltj6RNldCGBMsifZqfN+IKX7B2zKvq/WB3puoGOFHdOjFqJxHi60N0O6dlQI9Ye29f/+U2dGf+TYFq3lZLvwZTWQzR//G4MYcMPxPg+uZ5GLnVdtyI6y7+bqV5PA=,iv:O9RqO2nGPlkJa7giAsBqodYtsJsdbnePjuN5Y2dyyV4=,tag:C3fsfHwyRGKsysd88P8asg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
