vaultwarden:
    admin_token: ENC[AES256_GCM,data:D7z1tZhOSDmGIgjU1ihd+kjvaMNJho0TBz4P+faEUKimu60gWUf4Vs9R5PW999ZXjfFfxwjtSKOl2+Anf+j+x/ANAun2swTd/hjzhCGfVAEnr0s2SOg1VLx9QYiQACsvUX57DOgNG+uXlF1c9gWwJ++9SU9jtw==,iv:lZX/J4X3rH58TY8XuEQ8hFVxl9T/llA3JxyAqrdjWzo=,tag:NCOzwE4QhzjZ/BLoX907LQ==,type:str]
cloudflared_tunnel_uuid: ENC[AES256_GCM,data:vLXeDv5zbzJEJ6ocBN9yu1eRcFB627WMJENShRW6ur/0RPZf,iv:81Wgd9+OAg1QB6DlCj88+GWfNbYMKeqUaFVCYKqDLu4=,tag:qwuzxtUolaBRl3sR/fNHlg==,type:str]
hermes:
    hermes_dashboard_basic_auth_username: ENC[AES256_GCM,data:VshipXGTfw==,iv:jENs0Qe4zeh4BiukRY8X+nLueWqIEEQ9SvP4+dFzAks=,tag:LpL2cF/q+G6uyOIEgF8d3Q==,type:str]
    hermes_dashboard_basic_auth_password: ENC[AES256_GCM,data:GoWexaz8MvNcffx4C9j/TDsb/5faELqDmwbIb/xdihQ=,iv:rNbAiYDFt4+LblkbvGT7TAigdXfWV8dxtn9GKsBWOX4=,tag:nsnYRoTorup+0vh/cjrauA==,type:str]
    hermes_dashboard_basic_auth_secret: ENC[AES256_GCM,data:Ltu3b5YnU7FLN8SaT3cztLuaNaDCZt5qJlsJ0PGczuFlZnWScZJEHqEGo1M=,iv:tamUb6Pwpr2bkQoJM5WI8TTxHhTqpk4XB+OmaKQtJ7A=,tag:n5G7Ila/LG9o94444taG8Q==,type:str]
    opencode_go_api_key: ENC[AES256_GCM,data:aCqHX0erWAPyj6gLoMI/y/3NT5Y84UhQ6L8e7Q4Xpsb9TRHQe5PkZUZG+Rq6SByi/GNPLIvRMbh2qp7tWg2nLP5XSA==,iv:EOfg4qYslM8N44kLsLIZqb/BoSh5heLYB6TVbZwBMxY=,tag:CiUg1tMKizkn19BqZWy+gw==,type:str]
    telegram_bot_token: ENC[AES256_GCM,data:G96hrtmPtkQzA1hDV2On5UgKxR6NK52UV/Nl2GSvEPE8CigoE3mxrO3vmoqPLA==,iv:3CNdRdnndmsSF6tOE6lvs8lwqpwTScKBAa3p7BcH6LM=,tag:UWTFZOFUV7NOo4Q97g9FsQ==,type:str]
    telegram_allowed_users: ENC[AES256_GCM,data:xeGoGGzmgQ7YPJr1nuYrwdB7o+As,iv:1WIL8GB4oQI3e5yZnyWTN+i8+TYlC5KG71jz5bMxKfE=,tag:nsjecMCr2KyAbOnwKLwTMg==,type:str]
    telegram_home_channel: ENC[AES256_GCM,data:Pkg2pCdneb5S3Skc9vM=,iv:8+BWQ013cGMtmV99fVHKIi3VBbhf9z7lSG9CGkZw3+A=,tag:HdP/QDq6wjXuWbovD3JD/g==,type:int]
sops:
    age:
        - recipient: age1paqwux2ffqspe3ltux45wvn2vzdy24hwj8utgt0en64afeys4vuqxjpcvl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByRWNLZ0NqUVY0S0dJS0FS
            RSsrUkFqRk92blFaRDl3VlJTaUhGQ1RlK0VrCkV2SFgwdE94emIxNkFVQy9DR3N4
            U1dSOFE3ZmxmVlhyNFNTcWpGOXlYeUkKLS0tIE5qMnNMMnp5bUllN2k0RUQ3QUNT
            ZjNwbVNCNVZsdGxxNGVOQTFNSjFuSjAKQDoCpvf66FcYuD9eEZlj5/Rh0/Fknxkh
            lCBvYcKRz90KN5S5GonH+CzbGnlSK66MKwLDIb4mf1tUGI98HgqSag==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-02T11:59:37Z"
    mac: ENC[AES256_GCM,data:EnK8BK+Tk/ZcR/Jk5fDr+RuUh2qxBVdeplpaOQzx0t0Pgu0Ly7JkacPouO9rqbmldOYXDyA4GbQQ6gZ9hai9SOZJqbiSUZfgAv8OUuMxUk9S7qNFcSIegtP5/QRIAPM9JuK15rPfEEFDkIblogO6OZIMBV7WNnDGWplT+tYSweU=,iv:ZZ3csoDaoG07W9EpJ9Nb3tQqMuel5fl/1qjkQDaQwiA=,tag:1pW56kGWLYlSsxmWKhoX4w==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
