- name: Create synapse directory
  file:
    path: /var/www/synapse
    state: directory

- name: Copy docker-compose.yml for synapse
  template:
    src: synapse_docker-compose.yml.j2
    dest: /var/www/synapse/docker-compose.yml

- name: Check if synapse container is running
  shell: docker ps --filter "name=synapse" --format "{{ '{{.Names}}' }}"
  register: synapse_container

- name: Generate synapse configuration
  command: docker-compose run --rm synapse generate
  args:
    chdir: /var/www/synapse
  when: synapse_container.stdout == ""

- name: Start or restart synapse container
  docker_compose:
    project_src: /var/www/synapse
    state: present
    restarted: yes
  when: synapse_container.stdout != ""

- name: Start synapse container
  docker_compose:
    project_src: /var/www/synapse
    state: present
  when: synapse_container.stdout == ""

- name: Create .well-known directory
  file:
    path: /var/www/synapse/.well-known/matrix
    state: directory
    recurse: yes

- name: Copy .well-known/matrix/client file
  template:
    src: .well-known.matrix.client.json.j2
    dest: /var/www/synapse/.well-known/matrix/client

- name: Copy nginx configuration for synapse
  template:
    src: nginx_synapse.conf.j2
    dest: /etc/nginx/conf.d/synapse.conf

- name: Restart nginx
  service:
    name: nginx
    state: restarted

- name: Obtain SSL certificate with certbot and Cloudflare
  command: certbot certonly --dns-cloudflare --dns-cloudflare-credentials /etc/cloudflare/cloudflare.ini -d {{ synapse_server_name }} --non-interactive --agree-tos -m yamisskey@proton.me
  when: matrix_use_ssl

- name: Stop cloudflared service if running
  systemd:
    name: cloudflared
    state: stopped
    enabled: false
  ignore_errors: yes

- name: Find cloudflared UUID file
  find:
    paths: '/home/{{ ansible_user }}/.cloudflared'
    patterns: '*.json'
  register: uuid_files

- name: Set tunnel UUID
  set_fact:
    tunnel_uuid: "{{ item.path | regex_replace('^.*/(.*)\\.json$', '\\1') }}"
  loop: '{{ uuid_files.files }}'
  when: uuid_files.matched > 0
  changed_when: false

- name: Fail if no UUID file is found
  fail:
    msg: 'No cloudflared UUID file found in /home/{{ ansible_user }}/.cloudflared'
  when: uuid_files.matched == 0

- name: Debug tunnel_uuid
  debug:
    msg: 'Tunnel UUID: {{ tunnel_uuid }}'

- name: Set cloudflared config.yml content
  template:
    src: templates/cloudflared.config.yml.j2
    dest: /etc/cloudflared/config.yml
    owner: 'root'
    mode: '0600'
  notify: Restart Cloudflared

- name: Install cloudflared as a system service
  command: cloudflared service install
  args:
    creates: /etc/systemd/system/cloudflared.service

- name: Reload systemd to apply new service file
  command: systemctl daemon-reload

- name: Start and enable cloudflared service
  systemd:
    name: cloudflared
    state: started
    enabled: true
  become: true