- name: Create synapse directory
  file:
    path: /var/www/synapse
    state: directory

- name: Copy docker-compose.yml for synapse
  template:
    src: synapse_docker-compose.yml.j2
    dest: /var/www/synapse/docker-compose.yml

- name: Check if synapse container is running
  shell: docker ps --filter "name=synapse" --format "{{ '{{.Names}}' }}"
  register: synapse_container

- name: Generate synapse configuration
  command: docker-compose run --rm synapse generate
  args:
    chdir: /var/www/synapse
  when: synapse_container.stdout == ""

- name: Check if secrets file exists
  stat:
    path: '{{ synapse_secrets_file }}'
  register: synapse_secrets_file_stat

- name: Generate registration_shared_secret if not exists
  shell: 'cat /dev/urandom | base64 -w 0 | fold -w 100 | head -n 1'
  register: registration_shared_secret_output
  when: not synapse_secrets_file_stat.stat.exists

- name: Set registration_shared_secret fact
  set_fact:
    registration_shared_secret: "{{ (lookup('file', synapse_secrets_file) | from_yaml).registration_shared_secret if synapse_secrets_file_stat.stat.exists else registration_shared_secret_output.stdout }}"

- name: Generate macaroon_secret_key if not exists
  shell: 'cat /dev/urandom | base64 -w 0 | fold -w 100 | head -n 1'
  register: macaroon_secret_key_output
  when: not synapse_secrets_file_stat.stat.exists

- name: Set macaroon_secret_key fact
  set_fact:
    macaroon_secret_key: "{{ (lookup('file', synapse_secrets_file) | from_yaml).macaroon_secret_key if synapse_secrets_file_stat.stat.exists else macaroon_secret_key_output.stdout }}"

- name: Generate form_secret if not exists
  shell: 'cat /dev/urandom | base64 -w 0 | fold -w 100 | head -n 1'
  register: form_secret_output
  when: not synapse_secrets_file_stat.stat.exists

- name: Set form_secret fact
  set_fact:
    form_secret: "{{ (lookup('file', synapse_secrets_file) | from_yaml).form_secret if synapse_secrets_file_stat.stat.exists else form_secret_output.stdout }}"

- name: Save secrets to file
  copy:
    dest: '{{ synapse_secrets_file }}'
    content: |
      registration_shared_secret: "{{ registration_shared_secret }}"
      macaroon_secret_key: "{{ macaroon_secret_key }}"
      form_secret: "{{ form_secret }}"
  when: not synapse_secrets_file_stat.stat.exists

- name: Add required configurations to Synapse configuration file
  template:
    src: synapse.homeserver.yaml.j2
    dest: /var/www/synapse/data/homeserver.yaml
    owner: root
    group: root
    mode: '0644'
  become: true

- name: Start or restart synapse container
  docker_compose:
    project_src: /var/www/synapse
    state: present
    restarted: yes
  when: synapse_container.stdout != ""

- name: Start synapse container
  docker_compose:
    project_src: /var/www/synapse
    state: present
  when: synapse_container.stdout == ""

- name: Create .well-known directory
  file:
    path: /var/www/synapse/.well-known/matrix
    state: directory
    recurse: yes

- name: Copy .well-known/matrix/client file
  template:
    src: .well-known.matrix.client.json.j2
    dest: /var/www/synapse/.well-known/matrix/client

- name: Copy nginx configuration for synapse
  template:
    src: nginx_synapse.conf.j2
    dest: /etc/nginx/conf.d/synapse.conf

- name: Restart nginx
  service:
    name: nginx
    state: restarted

- name: Obtain SSL certificate with certbot and Cloudflare
  command: certbot certonly --dns-cloudflare --dns-cloudflare-credentials /etc/cloudflare/cloudflare.ini -d {{ synapse_server_name }} --non-interactive --agree-tos -m yamisskey@proton.me
  when: matrix_use_ssl

- name: Stop cloudflared service if running
  systemd:
    name: cloudflared
    state: stopped
    enabled: false
  ignore_errors: yes

- name: Start and enable cloudflared service
  systemd:
    name: cloudflared
    state: started
    enabled: true
  become: true