linode_prox_cloudflared_tunnel_uuid: ENC[AES256_GCM,data:oQ7AyqHp6B63RklGj++6gGlOEgCFdz48NF+npPkTCRcZlr94,iv:gQHCLLdA34CKo1ZJUDGk99K5IC9vgMQ1qXbdFIwtCt0=,tag:2vQlszxfUFhtq+4i4HROuw==,type:str]
matrix_rtc:
    turn_shared_secret: ENC[AES256_GCM,data:iMSpKAib7twukBjOiTj7ohXZ4MdRTvADROl0cn+rf0vcAf+8xzu/PK9QPU6xKkEpXQvmqPshJobddLqO3v7yEw==,iv:hvau4ZTrSkrd4+Bcauc1v84lYfVGjqh/Yj8GsQkAGHU=,tag:rc9vOJf6rat8hWxywPs+5w==,type:str]
    livekit_api_key: ENC[AES256_GCM,data:4KOZkxxot82kOOAX,iv:tkTdgV3XpL+w5t3hRFYZknYy9es8FxknUEQS/bZWRoM=,tag:am9X4GHhIQhMERJZw+qkjw==,type:str]
    livekit_api_secret: ENC[AES256_GCM,data:f8vKXFuq8jX1FZIr0ucvBK40rTEElpOJYmnDnfDD4aT1zFA/L2vuK4jp1hxn6JOo0HTnjKF3RwLaoWt7Xw+xzA==,iv:LfuEqypvhYyPcnjQ0RAwhiafUCVES21gQ/zbgfNKuF4=,tag:lyALQwmSvc0Vz2JMyj/LLw==,type:str]
sops:
    age:
        - recipient: age1paqwux2ffqspe3ltux45wvn2vzdy24hwj8utgt0en64afeys4vuqxjpcvl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDUlJhV013UEhXTXpMVm5D
            b0dMUXdVMTNUR0RZS0FuOWcxM2VyWktydURNCm5oT2g5amM0QWpDVTBjQ3dxcTRx
            WTZ2ZTNaZ3pZTDR4RG8xS3gwNVlvTEEKLS0tIDVkMjRacXFWUE9SN1FrWjRzYWI2
            QXJQYW1vZ2kxWW5vTXBEcUZFVGZGcHcKkvjre9aQRcv8XXMA0GmOp9gcvP9hFrKX
            wIVFwuFjFvsiELzxN2rmmZNBlQXtFaSVGe9kDlqyYE6oAg/o3IJedA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-13T01:45:30Z"
    mac: ENC[AES256_GCM,data:44OxEE46TSie+uXpa2pBaQBViDqjOd/QdGQsvJnN0NBTuYM323kfRPr4NJEM/ft/CnnNyWf898odF32TGZvljd0L+G0ah36ASoZuyMLYKRP2A0aeY6kAnRtfUnC4LqBZs9P94RcH9/wZd8XD6q1GOliXNKziYj6e1KHpOXD0hVc=,iv:Zg4/48Zq7/UVfA0fhh6dSpL+2jzRGyxDHIDHaGsO/M4=,tag:pL/t+Ie465BWFolR2bJa3Q==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
