- name: Ensure SearXNG directory exists
  ansible.builtin.file:
    path: '{{ searxng_dir }}'
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Clone SearXNG repository
  ansible.builtin.git:
    repo: '{{ searxng_repo }}'
    dest: '{{ searxng_dir }}'
    version: master

- name: Configure .env file for SearXNG
  ansible.builtin.copy:
    dest: '{{ searxng_env_file }}'
    content: |
      SEARXNG_HOSTNAME={{ searxng_server_name }}
      SEARXNG_ADMIN_EMAIL=admin@{{ domain }}

- name: Generate secret key for SearXNG
  ansible.builtin.command: 'openssl rand -hex 32'
  register: secret_key

- name: Insert secret key into SearXNG settings.yml
  ansible.builtin.lineinfile:
    path: '{{ searxng_settings_file }}'
    regexp: 'ultrasecretkey'
    line: 'secret_key: {{ secret_key.stdout }}'

- name: Temporarily disable cap_drop for initial setup
  ansible.builtin.replace:
    path: '{{ searxng_dir }}/docker-compose.yaml'
    regexp: 'cap_drop: - ALL'
    replace: '# cap_drop: - ALL'

- name: Start SearXNG Docker container
  ansible.builtin.docker_compose:
    project_src: '{{ searxng_dir }}'
    state: present
    restarted: true

- name: Re-enable cap_drop for security
  ansible.builtin.replace:
    path: '{{ searxng_dir }}/docker-compose.yaml'
    regexp: '# cap_drop: - ALL'
    replace: 'cap_drop: - ALL'

- name: Create systemd service file for SearXNG
  ansible.builtin.copy:
    dest: '/etc/systemd/system/searxng-docker.service'
    content: |
      [Unit]
      Description=SearXNG Docker Service
      After=docker.service
      Requires=docker.service

      [Service]
      Restart=always
      WorkingDirectory={{ searxng_dir }}
      ExecStart=/usr/bin/docker-compose up
      ExecStop=/usr/bin/docker-compose down

      [Install]
      WantedBy=multi-user.target

- name: Enable and start SearXNG systemd service
  ansible.builtin.systemd:
    name: searxng-docker
    enabled: true
    state: started
