#ENC[AES256_GCM,data:RB0AxmDyPA5aph302t77imc70F2AdABV2+IvBApRmtVRIkjznaTHx8kRfMMiAN4nTDhr3g==,iv:zMu9oCkSAjqlbMYJFTjmb7RWgRXTogNrvTDYWEVLVFc=,tag:c5lTrrvShGUG1KqK4/7mPw==,type:comment]
#ENC[AES256_GCM,data:P/veeZ/xDM3tg7D9nVMCc/3YEPTPJcaQxw==,iv:LlyhVzR/2cieRMBETIpryK4axRfdraMnvQIYx5OZ3XE=,tag:7z3kf/ljkABM0aMC9OR/pg==,type:comment]
ctfd:
    secret_key: ENC[AES256_GCM,data:ELHLSqZZvDQ3muhf3Odt3+jYJbooLtHaZ2G6kQ0pi0VoVAdP510rjopLgNmh7ebbJhhsu4dbFpYEnQn6Xe0uHw==,iv:AHu1MTwh1tgF/HLMkt/WqvVonT7up5GBZnAJPf3mnE4=,tag:kcsmMcZIL9AMtxpNhyY/uw==,type:str]
    mysql:
        user: ENC[AES256_GCM,data:pjxvfw==,iv:ShxUXNtxp9/+69tUB14nkvumLxy4RxImGomcyF1C2XE=,tag:mf6xZc1Um+h8ZAONv9z/7A==,type:str]
        password: ENC[AES256_GCM,data:oUWVAX4pG+VbwDQybH4mynzvu33EXL4CsIoVXGyysS4=,iv:lqvcO9KLKIDz/BTTXtEWF2/YvV6KNCYLCkX2tmW2Mxo=,tag:gxc1cFBLPqe06+u+QBzgGA==,type:str]
        root_password: ENC[AES256_GCM,data:SzqpaM5yYeZNOjeSoRDhH20NUI7WRIbfWDhv65qrQd0=,iv:a65S8wtmks9avzb83bA4RA3C1uIq68Or8zSvzkjVn3M=,tag:rzy5K4eFzKnWFpZ9xbpvXA==,type:str]
        database: ENC[AES256_GCM,data:buIrNQ==,iv:5FN4ufcra3QU0YqUbWTUa5EH4ufXgulxHndKIBKnFpk=,tag:e/dTNkTUR3xG1Ov0WrZraQ==,type:str]
cloudflared_tunnel_uuid: ENC[AES256_GCM,data:4A5bhRNAjYSgcuFgjcHmgX7N2ZSBcAicGRHxlr+bC+hyyOHq,iv:lVrzxvvPvfwddfy9EhZbdhXoyspLCLuApcGtAEzEb+s=,tag:A03bhibi2zB5V4lFchASww==,type:str]
sops:
    age:
        - recipient: age1paqwux2ffqspe3ltux45wvn2vzdy24hwj8utgt0en64afeys4vuqxjpcvl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1dndqZlpiTnF2dUdZQTlJ
            RWV3L0ZxaG4rZ1JqN0FjMlUxVktPWVhYK1RjCnUxTG1xQW9Rd0s0amVSNURDMjhX
            QkpGcHJCWHliSHhlazRDRFlSSmlrSmcKLS0tIGl2ZTFxYnRmbTBUVHBScTZTWlRq
            R2Y2MnB5WTloRU84NlkxYjFQRk5lV0UK+XnQEB2eKfliTyVXTH7IC56uLX0yrt19
            mWQI0pROCg8XsoPMsJRneeHKmdW8S7Gt2sXHtVcL+Gn+P/h9surrog==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-17T08:27:17Z"
    mac: ENC[AES256_GCM,data:rcShMXAiLK+dXXEp5j+q8HCVv9tNXZAXSnSnJglNOm+WHhesioa+lHg1lzObm/YPj++lPzEKsbTm7NLOi6414iCnfjiKIrQR4ojfxTRJ8SXAa8stLk0nyqVcTsWntpM/6L2BaI3PT+ydse6gqaLeCt/Ja+lVeLad9rJ9TQ1COso=,iv:KnrkIqyfihveaSEAaf7yb2BnoYidV9vRqaedGLl9KyI=,tag:n7zVKM3KUZtA7kCfQo6lBQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
