- name: Restart Cloudflared
  systemd:
    name: cloudflared
    state: restarted

- name: Restart Docker
  systemd:
    name: docker
    state: restarted
  become: true

- name: Reload Nginx
  become: yes
  become_user: root
  systemd:
    name: nginx
    state: reloaded