#ENC[AES256_GCM,data:A4kZXrHU5kgd83dU0gtzYH7dbih8VtVlcx9yyM0mT7JR3MGaozG4GnYiXbR7bQ==,iv:rTykD8s/ULR3zalHJnvGYTSO2JhqbDgBKtqRu1KPaLQ=,tag:r06w0/zIkV4tTdxSONh9Yg==,type:comment]
#ENC[AES256_GCM,data:apyfXyOLA11BVHyZfmP025vq49Iz5veFWr2q0ZCLl3iEz9zAGXU=,iv:qKrnh8MN7HDWt49IAmQczQOK5cvxdhQJwyvcJa2DACM=,tag:ldh1kCXDruuizIrZCrruyg==,type:comment]
#ENC[AES256_GCM,data:k+kP4CBt+Qhenkj53A==,iv:lamYvSJFND1RFr7ztVLRRTM8H3y8UprMZYqMxNdiIcI=,tag:/xcCKBvhHxlAIO82uvIEgA==,type:comment]
misskey:
    db:
        user: ENC[AES256_GCM,data:ddc4s32WbbW9Qvp+Mqf04GmJnbHrbqmwvh4cYx3J,iv:WrWAnI+UnSfQ33wcEMWruabDwD/SjSBRYbvpOAmsTSg=,tag:M1bbmGL/eTXAVTi30tN2cw==,type:str]
        pass: ENC[AES256_GCM,data:JFD6lxyOMM+MqNgJ5nYy5GBx4Uh7ErFX,iv:RkTnmpmJ6XYLp3Xw3N161V3tU3lpuAjMxUw5rPJ9qqA=,tag:/MZXUgQZ/54RHFi/xhACoA==,type:str]
        database: ENC[AES256_GCM,data:mskUWFqsa1cN3/Pu7mQ=,iv:ClfuF3RWFI2nQ2Nh1uIOpiQs3ksdHrk7cJDEBGcoLN4=,tag:iQ2D4Mv+eGyckFF3HX1ojw==,type:str]
#ENC[AES256_GCM,data:PLbP6NeaGlFzS1j8f7LWP7sFbJdL+D+gK2U/h0mhHX4=,iv:sPNRUZ33uBscHD44RGr2bI+/wmc7WsARbbQC+AVq9u4=,tag:hDyq3Rx8mVcRtuMBCZfT8g==,type:comment]
mcaptcha:
    postgresql:
        user: ENC[AES256_GCM,data:0kAaN0Y0p6c=,iv:r2+1vbb2S7n/LtMyIML2OzFkIm2OATuC6IlqkeBlIgQ=,tag:h1eiXaAjjho3c689fG5hzw==,type:str]
        password: ENC[AES256_GCM,data:K3wJ9WwbCCG+I2lueuEwc/CzoyobjTHQWBpV3L97YPjtgPgXhGjWl/pqzQ6zn/Dg/UUjXceCkeaTVQCByelmzg==,iv:8B7eDS01e4PKCiDTAEBNVjhfkVdKbv0TtBQ15tG1afo=,tag:1PDA4P421xa/T7k9RRmyzA==,type:str]
        database: ENC[AES256_GCM,data:XK8Cc/8Vn3U=,iv:SMtxri1XouGYrJo6fCzwMyymLIsecdVCkpdza9RuELo=,tag:ZhRjEkBbTB78WhTx7jg2yw==,type:str]
    cookie_secret: ENC[AES256_GCM,data:jMaAgIBVfgUBTKJz9pgsGqovc37lcdao0uYUurd4WUZJQimYy0enZHPE6001IB0ySCS1cudBEJttAMKerLVhlQ==,iv:I/uO5xGW9A6ZR/L2oxvv39FfnGn2YBb7hLgmZiPgzJ4=,tag:pWNUR7P4dpzc+hmfZS0EbA==,type:str]
    captcha_salt: ENC[AES256_GCM,data:JVL4I02nxxzvZy4C8ytcSfO6McVEHbZJ7Egl/bpQT1/AzIGgncJqh8L8fAn2UQxor/Z5uPCvxF+QyxJktM+/cA==,iv:IG1DCCcgiq/PByW7q7iDrjf5okIKE9LIZhdWa+xYgMQ=,tag:N8qPSCsBLXgZlOqJ7uZkBw==,type:str]
#ENC[AES256_GCM,data:AvD4K/gVhSHFz+Npr2eGBfapzlMg4bF34eucSc0y1idd,iv:CAVawEgJnR0vOTLHhQWYaHF4EO4XlcivYeXXM66b7+k=,tag:UobXDy1vl0WyTzAWfr4U+w==,type:comment]
authentik:
    secret_key: ENC[AES256_GCM,data:1vgyQ8arzf/hE5cm1CGUuxTmE/K46mp8m/6LQnoalmzSmMjP4tP4vyRdvlvk9mnKicU=,iv:kJB/cQZvYdyv+CFghtei0FVeQtMCI+b65mrlxINNimA=,tag:Z4RmtgjQ+Ii29FOc6jX4ag==,type:str]
    postgresql:
        user: ENC[AES256_GCM,data:tAMMhXJzWS3c,iv:t/emeKLj9HPTwCS6gjTX/8UFS0iEz5Fl1iwAVQz4hkk=,tag:WjwcSTRe5LXhfNt/tAAvEQ==,type:str]
        password: ENC[AES256_GCM,data:EglcAQxOX3uGOCiZRsgmEaVJ0Hzly9lIqA18vQyLG7Y=,iv:5MZkgtqJA47pDau3KFX0zrGa60V6dwQrQ0P7wi76BmY=,tag:+AZevGpCLzZHsc3g8iISHQ==,type:str]
        database: ENC[AES256_GCM,data:o7eftY7k9HQR,iv:uZPeS3prhRZ2dPLVWeugADcy13/cvcEBC8fx22wH22c=,tag:2fAJaiD6hX3moFFM5hScmA==,type:str]
#ENC[AES256_GCM,data:OfnvAp3P92FdAOIE+4y22bMyCyS9TBIbM4GUm6g9,iv:2Z2Oki2cs/7txB5IL5Hla5C4+ultp/FhfEzxQEvGTgQ=,tag:uMBt7eoQ2FypOxS4yclfXg==,type:comment]
yamix:
    postgresql:
        user: ENC[AES256_GCM,data:WXN9TTE=,iv:2k2YQnFOqKYT6fskEnbLoWiBZ4tGCxINZtMwDYkmBMM=,tag:045HxhTqiR6EKe9pfKwnow==,type:str]
        password: ENC[AES256_GCM,data:A4+veGwwzJ8oygbkCYeZNdg+tM4LwSRqImjofnK+m2n7yJD/H2YYhvqSAyvnDKXd,iv:AaaUDYndNpwFjkeNtlncDM8xGUwxcndd9T5NTwNKYIU=,tag:hkWPzJ/KqqtDm6tOhOY/AQ==,type:str]
        database: ENC[AES256_GCM,data:BntD+8c=,iv:VtRygucxyJkeZ1ExZaPYR2hdMNmtFr4hwe254CzKoKU=,tag:d8zJM9moKioP1dJmi+Wg4g==,type:str]
    openai_api_key: ENC[AES256_GCM,data:adVSjfgW4A7ESSWvw3MJPaJCJy6uBgDl2aaTkJ+tkPA0/2yZ1btt2xxpzlyGurRkyq1jUoIqnxMAf2CAMlZfD4IJs6byKvwIsvfqkajBHqunCy0/R1lb7LDpzldHRjHtBE1/q9w6jZN7RHT2udP7d5wMD0RKVr6j94kQwQ6j0zyEceQIXEjeJZp5NDmoyJDRPViCrIMljXU1ceVdGsh89HeKHkw=,iv:gePcgF9UluGvz2QgLs81LePqSiDeNznhS3c/mzI2I4I=,tag:Jxf/gXn65YY0Jte71QtVmA==,type:str]
    jwt_secret: ENC[AES256_GCM,data:HlfoEYzoDdNho39YfhrmvQZr95wSAvqGOsQ7VKj9EzQjtKSf3sz87Mgmt/UotD9Q98Ooq2Z8bYDTRYtxR/BuVA==,iv:F7IEmI40SliGBFIw5EOhoHWYEdzkRgmX+40bTJBycCc=,tag:jkR3kgmV1gh2dm0wfuBrvA==,type:str]
    yamii_api_key: ENC[AES256_GCM,data:R52zDNhTwPh6GH7naoOXyf8JQ+BVNZnf71CTSlqxEI2Aes2v0h7I58uLl6R0EuFhBYqqNVqiByZ85BWFmwQewQ==,iv:7AQaVsWBpVZJnw/CI1bbfWf29X9w+Zcl1XnSI6s2oOs=,tag:z3DrDeNmchTxwUyh0ksW3Q==,type:str]
sops:
    age:
        - recipient: age1paqwux2ffqspe3ltux45wvn2vzdy24hwj8utgt0en64afeys4vuqxjpcvl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyUDJGVWhpWFhrSTJLMkhB
            Si85NU5xdys1NVkwZ2VNRVpwT2JIS0wwVFJzClVqNGdrcy9HNGszOTg5RHhtTmh2
            WU40ZkdISzZJOWpqdFVnUjNpOFFwemcKLS0tIDZ5d043dnFobE5DbDdNdVZLaDJM
            R0d3Vnd5RUZCelJPTTMwRDROQ3F0QjQKpxisbEQ546bCWQ2J9Wrm3UrkD0vmF4we
            8mcDbtl67ALLvVcZgK+AXRec6XOH+jScfjbbN58cyRqJA6+LVy3vTw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-30T12:11:30Z"
    mac: ENC[AES256_GCM,data:6JsD9mwhoxeYO5WLKesO/sIimFmMl6TFpfjkoY4rZIIEI0P1UxqrgFOL3Sauy45TPIYKBqPp0BtWXkjd8G4tuZtrKhvEA6i+nCoxWeaHUA/CtTnJFxh/Eofenbsdm0DRFngcYCptArWOkzlJR/2bQmxtHlNM13eg6hzbrvWMAeo=,iv:xDJj7I249ZQn7qutBU7AhCe06Rkc79006DCE4sTjjeg=,tag:uN5ulDNxXMwW/NOLJIx4Qw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
