#ENC[AES256_GCM,data:c9upCH057pHuT7iSPj8+PJsA+K64XQN7lK+/8mjyl4WOm9+P0hA+w0clIQVXLw==,iv:NQbuGbuqi0N+0xFJQJqInH6yWZT0G5sE7S5ThLZeLC4=,tag:OfuE7yxHDUNYl0uE4YjFmw==,type:comment]
#ENC[AES256_GCM,data:z7J6G7aUo2udnUtEcyoGUb23vG2lCSapyNGF8+NGklwF3zSVMhY=,iv:p/zPm59xCYFQA3C7hnPauz1GLglvXdmZT43lrZXYwjs=,tag:hTK68gfybiDnncVanVz6KA==,type:comment]
#ENC[AES256_GCM,data:lSOAOveRTYII0Dcjvg==,iv:WuNoRj1SXbyw8dhxfD9MxagSUkdnJCAlGGie2AqSAPg=,tag:FBDI7u9fU2EIyntXV4gy/w==,type:comment]
misskey:
    db:
        user: ENC[AES256_GCM,data:/5MGkWlqbTZOhyf4OikYxviAhYPVqZkFmtVvQ0MM,iv:DQAF7hdzfWPxIFCysWkK4RXgHb4m+eqWXfPmsjGA+7o=,tag:pGFHLK1dt1eGS/y8Hoassw==,type:str]
        pass: ENC[AES256_GCM,data:/etUix2I0fYfBVEIBnX/JLoXGcREVRRK,iv:6v9+dEacicXz1zmHZZxVChuTZyRgny22jh/chcbqqS4=,tag:9VK3HBKAyQLvk1TTMS8vBQ==,type:str]
        database: ENC[AES256_GCM,data:1Q1taIxZeE/PAbIposs=,iv:ACyfuRb2xx+jWHUcPUrNfiEm4jhc2nC15U6N8vIpwyE=,tag:xxg7yjfLQYDiV8CAl6Qp2A==,type:str]
#ENC[AES256_GCM,data:VFNjpqzJ9tnEGYlDeCCFUWRzGjlWnp/1wS+qQOBd,iv:ZI7VeX+Z6EEVbNL/8y+tMl5zmK+T8797hbKiPlLQsLI=,tag:VyCH8s9MMDjXkjqeaRBgjA==,type:comment]
yamix:
    postgresql:
        user: ENC[AES256_GCM,data:RYf+dX4=,iv:xKR0pSfufQgWDYd/od0G8YvYWtVE1ci/oNGvLZ6KDhE=,tag:RX/V5u7Fr2BLyW98KMwIrA==,type:str]
        password: ENC[AES256_GCM,data:L4eGqYAk/AKoq5+SjX0YkvUzX5Jt5+bGMY2Iyq42h5bVLT6dza+DL9/4RkZz/8/M,iv:h+avyFoJSI8ZgET2oQ7g4mQO9UAtjYsAOcr1/m6JI6o=,tag:sfE4JgO2bXrhwNJ+US2AIQ==,type:str]
        database: ENC[AES256_GCM,data:MtAhddE=,iv:j1tEWipgaQiul2IJOQhUb6imjVXDSlota+F3yNPGnYQ=,tag:tfyN1H9l3O1QSoccT8SLtg==,type:str]
    openai_api_key: ENC[AES256_GCM,data:3BFF17LN/ycHvn1frwhGVHLeMJFZYYtAv0CLtJ+I6qBsbaZzG18Donw+0byrkoW2NRPvzumamAV2Ovrz0tQpIJehXuAIpESmsQ==,iv:Mrjd6SjzCoF/ahh/ZHvLfYFCFZdTLRWJR+C2FmG1xRc=,tag:Hbcx0HxO1Z2J6WgC6Hr3IQ==,type:str]
    jwt_secret: ENC[AES256_GCM,data:9OeWNiapgzz5+/WfyVBpCNHU0/ttVHVGp7RAy83zJUnQ/tcB8UJ21so02f29V3946h5ntGZaiY40GmBpfjAqXQ==,iv:48+by5iCb1psRnsrw8Q5YCHCir0xCuCseooV73BfmCo=,tag:T23TOOKPXxiYtOoSJDM6Vg==,type:str]
    message_encryption_key: ENC[AES256_GCM,data:kQUhk9FJPShZ/fost+4MiEL1yXmUIGFX7QcLYYXNJRP7V6iKdvFp6Vt1JKo=,iv:4WBO7k/ILQUI4edUt4OJUBsTWEVGJjd0lfO8vf0HAtg=,tag:WtkiNSgtXa+897Bq97+YXw==,type:str]
    yamii_api_key: ENC[AES256_GCM,data:pyMxhfb1EivJ3jSZ2IPzyZZ4NBWDbvTmLCVhJF7SylO2Z6S0NQHk5lBJ3oggC138/xL9tmI1sQv96IjyJtdkqA==,iv:Lc6q4OLCxi7aRaPtyzJc+mJ68jLF69U/062y7IkuJ3s=,tag:SwYcCryS5mW+Jau5lqis6g==,type:str]
#ENC[AES256_GCM,data:2UlYKswwsM1TlN9lIGPCzu9jP1aDMJif,iv:X5SsZjBcf7Nyp7gzObCNEARGfj8Rn/5Hb/CVfyLbZYU=,tag:ZAWygbyIaciiPtWe8vUG2A==,type:comment]
caspar_cloudflared_tunnel_uuid: ENC[AES256_GCM,data:Gpc3wiePel5e14+eiqUC+ny6nw/AgKDidzOWZ9Lrj6PryqkW,iv:n8UeolDm+Tf+YpN5o0EAMOfjCrk7SWb/bl0u3LeNFkU=,tag:SKKyYCAUxaieXkKzeS/UnA==,type:str]
sops:
    age:
        - recipient: age1paqwux2ffqspe3ltux45wvn2vzdy24hwj8utgt0en64afeys4vuqxjpcvl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxQ01DT0pQL0U4UXpkYk1Q
            SjVxSXNnb3h4cndRTkxjcGtGTncyam1KYUNNClpBVDRUUlJkckJwNFVsdjVBc3JK
            cGxFN0FSL0Y1S3JEcGU3WTJEeTBiQlEKLS0tIGoyVU9VR1ZmMTkrRzA1NFRRYThW
            TEM0MGFGVzhWcTAwS1ZkUEVWdDd4WDgK5b4Xw7FaKACsQt77vDGnrlThJTILfSMO
            6vxY6YA0atN4e336sFTTtlV6ZOWfEy+Zt8Vwt2Mf96ZDGAuDYpcZPA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-21T03:50:51Z"
    mac: ENC[AES256_GCM,data:x0b5ZDLLoLhWqBPOMB1YSCICfWRRM8AuZc2+1knP09HggJa2niiZ3pp6Z266V1BO9yb1ZYzil35Mu0GS33+5SOdfibBC4hvQXVZzpf8/181V3QU5iwlYEy0P7uwTkXGoed3g0i74DR1J/NOxiy8cvZL6X3bWXLfLSxxUJPKXyas=,iv:mmO7n6nYCa0mCm7DgBuEqM4Vz6H/Fs7rd4GG8qMvCik=,tag:Ny1kRgejTr63cd0eDDFp3A==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
