#ENC[AES256_GCM,data:c9upCH057pHuT7iSPj8+PJsA+K64XQN7lK+/8mjyl4WOm9+P0hA+w0clIQVXLw==,iv:NQbuGbuqi0N+0xFJQJqInH6yWZT0G5sE7S5ThLZeLC4=,tag:OfuE7yxHDUNYl0uE4YjFmw==,type:comment]
#ENC[AES256_GCM,data:z7J6G7aUo2udnUtEcyoGUb23vG2lCSapyNGF8+NGklwF3zSVMhY=,iv:p/zPm59xCYFQA3C7hnPauz1GLglvXdmZT43lrZXYwjs=,tag:hTK68gfybiDnncVanVz6KA==,type:comment]
#ENC[AES256_GCM,data:lSOAOveRTYII0Dcjvg==,iv:WuNoRj1SXbyw8dhxfD9MxagSUkdnJCAlGGie2AqSAPg=,tag:FBDI7u9fU2EIyntXV4gy/w==,type:comment]
misskey:
    db:
        user: ENC[AES256_GCM,data:/5MGkWlqbTZOhyf4OikYxviAhYPVqZkFmtVvQ0MM,iv:DQAF7hdzfWPxIFCysWkK4RXgHb4m+eqWXfPmsjGA+7o=,tag:pGFHLK1dt1eGS/y8Hoassw==,type:str]
        pass: ENC[AES256_GCM,data:/etUix2I0fYfBVEIBnX/JLoXGcREVRRK,iv:6v9+dEacicXz1zmHZZxVChuTZyRgny22jh/chcbqqS4=,tag:9VK3HBKAyQLvk1TTMS8vBQ==,type:str]
        database: ENC[AES256_GCM,data:1Q1taIxZeE/PAbIposs=,iv:ACyfuRb2xx+jWHUcPUrNfiEm4jhc2nC15U6N8vIpwyE=,tag:xxg7yjfLQYDiV8CAl6Qp2A==,type:str]
#ENC[AES256_GCM,data:etqhSjozSiB/64WEBkPAGLzfkVdHNLAyj8D2qkSZxIc=,iv:aVO6a3iGiFNUV7RSYPb1qf2UQwKh6OvgI/Q5YwfG5T0=,tag:UcFERTceL70j5kX7RVDwtw==,type:comment]
mcaptcha:
    postgresql:
        user: ENC[AES256_GCM,data:lCszRcu+34U=,iv:VXRZMx/u6DiUzkG29rRabpJYu/TyWlnokjgWnQwfDMQ=,tag:vqB/bkNp3fbhOxeAaHQj8g==,type:str]
        password: ENC[AES256_GCM,data:Br9hx/2GLlMHvs/4VeyfucVc2HSXx0hS0EnjR3sCtxwtTuSIjv8IlpIvFy3dJDT3xzOg4Ngz8p6dR1wA53SqrQ==,iv:Jp+AsuFnW945v2wB9hGGyai3Dm9+ZCUuimHgKRHaVxk=,tag:bPooLkhJQKgdkaK7E1lXYA==,type:str]
        database: ENC[AES256_GCM,data:RxMgZfRM54w=,iv:osR/MZC/o9QF45yes4dw2fgQBXuYP/yRiIZFVbbsPjA=,tag:qv02H+nP9JMWWpAnjU8rxQ==,type:str]
    cookie_secret: ENC[AES256_GCM,data:L2DOdHk3tqeHUO7eagndBWZ2A8m+pw5PzHxhZZ9yAtLDrchjvWMQ7DexKQcxIXZd0FmJ4d/DvOqOczBmL9XCcA==,iv:h5lijjMa5HrPEqqQUpY38N1MrxNRCAltGsZyIEgMM+0=,tag:/4jsQR25e0gAsbD4BPRfEg==,type:str]
    captcha_salt: ENC[AES256_GCM,data:NAcU4ZtAgTpttd0CYyzwNRkSI5TybouAFiDncRGNMg1G/53bjnN6eQXvDw5d11/DrAMmvw/r3K4DDGS8N08Bdg==,iv:a+iiEfT8ilUl5yk51oUDA4QXE33Zp225CH/lI+o19to=,tag:2kP2Cd/qMna2Stur2kRKeQ==,type:str]
#ENC[AES256_GCM,data:VFNjpqzJ9tnEGYlDeCCFUWRzGjlWnp/1wS+qQOBd,iv:ZI7VeX+Z6EEVbNL/8y+tMl5zmK+T8797hbKiPlLQsLI=,tag:VyCH8s9MMDjXkjqeaRBgjA==,type:comment]
yamix:
    postgresql:
        user: ENC[AES256_GCM,data:RYf+dX4=,iv:xKR0pSfufQgWDYd/od0G8YvYWtVE1ci/oNGvLZ6KDhE=,tag:RX/V5u7Fr2BLyW98KMwIrA==,type:str]
        password: ENC[AES256_GCM,data:L4eGqYAk/AKoq5+SjX0YkvUzX5Jt5+bGMY2Iyq42h5bVLT6dza+DL9/4RkZz/8/M,iv:h+avyFoJSI8ZgET2oQ7g4mQO9UAtjYsAOcr1/m6JI6o=,tag:sfE4JgO2bXrhwNJ+US2AIQ==,type:str]
        database: ENC[AES256_GCM,data:MtAhddE=,iv:j1tEWipgaQiul2IJOQhUb6imjVXDSlota+F3yNPGnYQ=,tag:tfyN1H9l3O1QSoccT8SLtg==,type:str]
    openai_api_key: ENC[AES256_GCM,data:tM6gd4JPiYIj23nk9ar3mh14OSt9ebqU60xEQEcBwFkXegrToOLb1aAt44XTrnX3k3m/ksHp4UkMrnjYG76NbCYBIfkVWQ4f7/4W5t9RpcWB0wUXOxkQm8lAs0hwYUMuAkhjMI6fxgGM6zB8wkD/zvh7NlJbx3SKQnwCgilAFrJklX/z5IYwUh1YDDuhTKkNgVj3E4OZcMNGgRoZQs+wzF96vmQ=,iv:Em2V7Ju6j2vRHikIljfj0o2nbJ8ec6g+Uft/LQcnekQ=,tag:bBFUH6t3L6GBZvwysCUhYw==,type:str]
    jwt_secret: ENC[AES256_GCM,data:9OeWNiapgzz5+/WfyVBpCNHU0/ttVHVGp7RAy83zJUnQ/tcB8UJ21so02f29V3946h5ntGZaiY40GmBpfjAqXQ==,iv:48+by5iCb1psRnsrw8Q5YCHCir0xCuCseooV73BfmCo=,tag:T23TOOKPXxiYtOoSJDM6Vg==,type:str]
    yamii_api_key: ENC[AES256_GCM,data:pyMxhfb1EivJ3jSZ2IPzyZZ4NBWDbvTmLCVhJF7SylO2Z6S0NQHk5lBJ3oggC138/xL9tmI1sQv96IjyJtdkqA==,iv:Lc6q4OLCxi7aRaPtyzJc+mJ68jLF69U/062y7IkuJ3s=,tag:SwYcCryS5mW+Jau5lqis6g==,type:str]
sops:
    age:
        - recipient: age1paqwux2ffqspe3ltux45wvn2vzdy24hwj8utgt0en64afeys4vuqxjpcvl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxQ01DT0pQL0U4UXpkYk1Q
            SjVxSXNnb3h4cndRTkxjcGtGTncyam1KYUNNClpBVDRUUlJkckJwNFVsdjVBc3JK
            cGxFN0FSL0Y1S3JEcGU3WTJEeTBiQlEKLS0tIGoyVU9VR1ZmMTkrRzA1NFRRYThW
            TEM0MGFGVzhWcTAwS1ZkUEVWdDd4WDgK5b4Xw7FaKACsQt77vDGnrlThJTILfSMO
            6vxY6YA0atN4e336sFTTtlV6ZOWfEy+Zt8Vwt2Mf96ZDGAuDYpcZPA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-13T01:16:56Z"
    mac: ENC[AES256_GCM,data:qUNIseXjlJE9WjDXl9bRvbxoZ4Ix0i9dSOeruSl/ypupavzLUxJRk1Tq9WAoCSkm6MAwr0yc/wiAR6RDbj6xWaKLm2J8EAk588qunfd2/4UxlCnYUZqQ+IvESxg6SirP+y0v74DF75VF5jtbRIQJIxCSTLqNDcMNHOS3IhbPD/4=,iv://QubxKdukXpG9Q+XL0WVwx9RuEyn7bFKjTDjYl/AAw=,tag:XWQYBjNLuFT56u+FGVMTNg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
