# secrets.ymlから既存の秘密情報を読み込む
- name: Check if secrets file exists
  stat:
    path: '{{ addy_secrets_file }}'
  register: addy_secrets_file_stat

# secrets.ymlから秘密情報をセット
- name: Load secrets from secrets.yml if exists
  set_fact:
    mysql_user: "{{ (lookup('file', addy_secrets_file) | from_yaml).mysql.user | default('') }}"
    mysql_password: "{{ (lookup('file', addy_secrets_file) | from_yaml).mysql.password | default('') }}"
    mysql_database: "{{ (lookup('file', addy_secrets_file) | from_yaml).mysql.database | default('') }}"
    app_key: "{{ (lookup('file', addy_secrets_file) | from_yaml).app_key | default('') }}"
    anonaddy_secret: "{{ (lookup('file', addy_secrets_file) | from_yaml).anonaddy_secret | default('') }}"
  when: addy_secrets_file_stat.stat.exists

# app_keyが未設定の場合に生成
- name: Generate app_key for AnonAddy if not exists
  shell: 'head -c 32 /dev/urandom | base64'
  register: app_key_output
  when: app_key == ""

- name: Set app_key fact if not exists
  set_fact:
    app_key: "base64:{{ app_key_output.stdout }}"
  when: app_key == ""

# anonaddy_secretが未設定の場合に生成
- name: Generate anonaddy_secret if not exists
  shell: 'head -c 32 /dev/urandom | base64'
  register: anonaddy_secret_output
  when: anonaddy_secret == ""

- name: Set anonaddy_secret fact if not exists
  set_fact:
    anonaddy_secret: "{{ anonaddy_secret_output.stdout }}"
  when: anonaddy_secret == ""

# 必要なディレクトリを作成
- name: Create addy directory
  file:
    path: /var/www/addy
    state: directory

- name: Create db directory
  file:
    path: /var/www/addy/db
    state: directory

- name: Create redis directory
  file:
    path: /var/www/addy/redis
    state: directory

# `addy.env`ファイルを生成
- name: Create addy.env configuration file
  template:
    src: addy.env.j2
    dest: /var/www/addy/addy.env
    owner: root
    group: root
    mode: '0644'
  become: true

# Docker Composeファイルをテンプレートから生成
- name: Add required configurations to Docker Compose file
  template:
    src: addy_docker-compose.yml.j2
    dest: /var/www/addy/docker-compose.yml

# AnonAddyのコンテナが実行されているか確認
- name: Check if addy container is running
  shell: docker ps --filter "name=addy" --format "{{ '{{.Names}}' }}"
  register: addy_container

- name: Generate addy configuration using docker-compose
  shell: |
    docker-compose run --rm addy generate
  args:
    chdir: /var/www/addy
  when: addy_container.stdout == ""

# secrets.ymlに保存（新規生成があった場合のみ）
- name: Save secrets to file
  copy:
    dest: '{{ addy_secrets_file }}'
    content: |
      mariadb:
        user: "{{ mysql_user }}"
        password: "{{ mysql_password }}"
        database: "{{ mysql_database }}"
      app_key: "{{ app_key }}"
      anonaddy_secret: "{{ anonaddy_secret }}"
  when: app_key_output.changed or anonaddy_secret_output.changed or not addy_secrets_file_stat.stat.exists

# AnonAddyコンテナを起動
- name: Start AnonAddy container
  docker_compose:
    project_src: /var/www/addy
    state: present
    restarted: no

# Nginx設定
- name: Copy nginx configuration for AnonAddy
  template:
    src: nginx_anonaddy.conf.j2
    dest: /etc/nginx/conf.d/anonaddy.conf

- name: Restart nginx
  service:
    name: nginx
    state: restarted

# Cloudflaredの管理
- name: Stop cloudflared service if running
  systemd:
    name: cloudflared
    state: stopped
    enabled: false
  ignore_errors: yes

- name: Start and enable cloudflared service
  systemd:
    name: cloudflared
    state: started
    enabled: true
  become: true