packages:
  - htop
  - net-tools
  - nmap
  - rsync
  - zip
  - nginx
  - certbot
  - python3-certbot-dns-cloudflare
  - tor
  - privoxy
  - mecab
  - libmecab-dev
  - mecab-ipadic-utf8
  - prometheus
  - rclone
  - fail2ban
  - unattended-upgrades
  - debsums
  - apt-show-versions
  - clamav
  - clamav-daemon
  - lynis
  - apparmor
  - auditd
  - sysstat
  - python3-passlib