- name: Create element directory
  file:
    path: /var/www/element
    state: directory

- name: Create element-config directory
  file:
    path: /var/www/element/element-config
    state: directory

- name: Copy docker-compose.yml for element
  template:
    src: element_docker-compose.yml.j2
    dest: /var/www/element/docker-compose.yml

- name: Copy element custom configuration file
  template:
    src: config.element.yami.ski.json.j2
    dest: /var/www/element/element-config/config.element.yami.ski.json

- name: Start element
  docker_compose:
    project_src: /var/www/element
    state: present
    restarted: yes

- name: Obtain SSL certificate for element with certbot and Cloudflare
  command: certbot certonly --dns-cloudflare --dns-cloudflare-credentials /etc/cloudflare/cloudflare.ini -d {{ element_server_name }} --non-interactive --agree-tos -m yamisskey@proton.me
  when: matrix_use_ssl

- name: Copy nginx configuration for element
  template:
    src: nginx_element.conf.j2
    dest: /etc/nginx/conf.d/element.conf

- name: Restart nginx
  service:
    name: nginx
    state: restarted

- name: Stop cloudflared service if running
  systemd:
    name: cloudflared
    state: stopped
    enabled: false
  ignore_errors: yes

- name: Start and enable cloudflared service
  systemd:
    name: cloudflared
    state: started
    enabled: true
  become: true