- name: Restart fail2ban
  systemd:
    name: fail2ban
    state: restarted
    enabled: true
  become: true

- name: Restart Cloudflared
  systemd:
    name: cloudflared
    state: restarted

- name: Reload Nginx
  systemd:
    name: nginx
    state: reloaded
  become: true