- name: Validate rsyslog configuration
  command: rsyslogd -N1
  register: rsyslog_validation
  failed_when: 'rsyslog_validation.rc != 0'
  notify: Restart rsyslog

- name: Restart rsyslog
  systemd:
    name: rsyslog
    state: restarted
  become: true

- name: Restart fail2ban
  systemd:
    name: fail2ban
    state: restarted
    enabled: true
  become: true

- name: Restart crowdsec
  systemd:
    name: crowdsec
    state: restarted
    daemon_reload: yes
  become: true

- name: Restart crowdsec-firewall-bouncer
  systemd:
    name: crowdsec-firewall-bouncer
    state: restarted
    daemon_reload: yes
  become: true

- name: Reload Nginx
  systemd:
    name: nginx
    state: reloaded
  become: true

- name: Reload sysctl
  command: sysctl -p
  become: yes

- name: Restart SSH service
  systemd:
    name: ssh
    state: restarted