- name: Restart fail2ban
  systemd:
    name: fail2ban
    state: restarted
    enabled: true
  become: true

- name: Reload Tor
  systemd:
    name: tor@default
    state: reloaded

- name: Restart Privoxy
  systemd:
    name: privoxy
    state: restarted
