- name: Find cloudflared UUID file
  find:
    paths: '/home/{{ user_name }}/.cloudflared'
    patterns: '*.json'
  register: uuid_files

- name: Set tunnel UUID
  set_fact:
    tunnel_uuid: "{{ item.path | regex_replace('^.*/(.*)\\.json$', '\\1') }}"
  loop: '{{ uuid_files.files }}'
  when: uuid_files.matched > 0
  changed_when: false

- name: Debug tunnel_uuid
  debug:
    msg: 'Tunnel UUID: {{ tunnel_uuid }}'

- name: Set cloudflared config.yml content
  template:
    src: templates/cloudflared.config.yml.j2
    dest: '/etc/cloudflared/config.yml'
    owner: 'root'
    mode: '0600'
  vars:
    tunnel_uuid: '{{ tunnel_uuid }}'
  notify: Restart Cloudflared

- name: Install cloudflared as a system service
  command: cloudflared service install
  args:
    creates: /etc/systemd/system/cloudflared.service

- name: Reload systemd to apply new service file
  command: systemctl daemon-reload

- name: Configure Privoxy
  blockinfile:
    path: /etc/privoxy/config
    block: |
      listen-address 127.0.0.1:8118
      forward-socks5 / 127.0.0.1:1080 .
    marker: '# {mark} ANSIBLE MANAGED BLOCK - Privoxy Configuration'
  notify: Restart Privoxy

- name: Stop conflicting services
  systemd:
    name: '{{ item }}'
    state: stopped
  loop:
    - nginx
    - privoxy

- name: Clean up Unix socket
  file:
    path: /var/run/tor-misskey.sock
    state: absent

- name: Kill processes using ports 80 and 443
  shell: |
    for pid in $(lsof -t -i:80 -i:443); do
      kill -9 $pid || true
    done
  ignore_errors: true

- name: Configure DNS
  lineinfile:
    path: /etc/resolv.conf
    line: 'nameserver 8.8.8.8'
    state: present

- name: Add secondary DNS
  lineinfile:
    path: /etc/resolv.conf
    line: 'nameserver 8.8.4.4'
    state: present

- name: Start Tor
  systemd:
    name: tor@default
    enabled: yes
    state: restarted

- name: Ensure Tor hidden service directory exists
  file:
    path: /var/lib/tor/misskey
    state: directory
    owner: debian-tor
    group: debian-tor
    mode: '0700'

- name: Configure Tor hidden service
  blockinfile:
    path: /etc/tor/torrc
    block: |
      HiddenServiceDir /var/lib/tor/misskey/
      HiddenServicePort 80 unix:/var/run/tor-misskey.sock
      HiddenServiceVersion 3
    marker: '# {mark} ANSIBLE MANAGED BLOCK - Misskey Hidden Service'
  notify: Reload Tor

- name: Read and display Tor URL for Misskey
  command: cat /var/lib/tor/misskey/hostname
  register: tor_hostname
  changed_when: false

- name: Display Tor URL for Misskey
  debug:
    msg: 'Misskey Tor URL: http://{{ tor_hostname.stdout }}'

- name: Save Tor URL in a text file
  copy:
    content: 'http://{{ tor_hostname.stdout }}'
    dest: '{{ misskey_dir }}/tor.txt'
    owner: root
    mode: '0644'