- name: Find cloudflared UUID file
  find:
    paths: '/home/{{ user_name }}/.cloudflared'
    patterns: '*.json'
  register: uuid_files

- name: Set tunnel UUID
  set_fact:
    tunnel_uuid: "{{ item.path | regex_replace('^.*/(.*)\\.json$', '\\1') }}"
  loop: '{{ uuid_files.files }}'
  when: uuid_files.matched > 0
  changed_when: false

- name: Debug tunnel_uuid
  debug:
    msg: 'Tunnel UUID: {{ tunnel_uuid }}'

- name: Set cloudflared config.yml content
  template:
    src: templates/cloudflared.config.yml.j2
    dest: '/etc/cloudflared/config.yml'
    owner: 'root'
    mode: '0600'
  vars:
    tunnel_uuid: '{{ tunnel_uuid }}'

- name: Install cloudflared as a system service
  command: cloudflared service install
  args:
    creates: /etc/systemd/system/cloudflared.service

- name: Reload systemd to apply new service file
  command: systemctl daemon-reload

- name: Restart cloudflared service
  systemd:
    name: cloudflared
    state: restarted
    enabled: true

- name: Reload Nginx
  systemd:
    name: nginx
    state: reloaded

- name: Ensure jq is installed
  apt:
    name: jq
    state: present
  become: true

- name: Remove existing Mullvad VPN configuration
  file:
    path: /etc/mullvad-vpn
    state: absent
  become: true

- name: Remove Mullvad VPN systemd service
  file:
    path: /etc/systemd/system/mullvad-daemon.service
    state: absent
  become: true

- name: Remove Mullvad VPN early boot blocking service
  file:
    path: /etc/systemd/system/mullvad-daemon.service.wants/mullvad-early-boot-blocking.service
    state: absent
  become: true

- name: Install Mullvad VPN
  apt:
    name: mullvad-vpn
    state: present
  become: true

- name: Retrieve Mullvad VPN token
  command: mullvad account get
  register: mullvad_account_info
  changed_when: false

- name: Set Mullvad VPN token
  set_fact:
    mullvad_token: "{{ mullvad_account_info.stdout_lines[0].split()[2] }}"

- name: Debug Mullvad VPN token
  debug:
    msg: "Mullvad VPN token: {{ mullvad_token }}"

- name: Exclude SSH traffic from VPN
  command: mullvad-exclude sshd
  become: true

- name: Exclude HTTP traffic from VPN
  command: mullvad-exclude nginx
  become: true

- name: Add routing rule to exclude SSH traffic from VPN
  command: ip rule add from {{ ansible_default_ipv4.address }} table main
  become: true

- name: Add default route for main table
  command: ip route add default via $(ip route | grep default | awk '{print $3}') dev $(ip route | grep default | awk '{print $5}') table main
  become: true

- name: Ensure Mullvad VPN service is enabled and running
  systemd:
    name: mullvad-vpn
    state: started
    enabled: true
  become: true

- name: Check Mullvad VPN status
  command: mullvad status
  register: vpn_status
  changed_when: false

- name: Display Mullvad VPN status
  debug:
    msg: "Mullvad VPN status: {{ vpn_status.stdout }}"

- name: Configure DNS
  lineinfile:
    path: /etc/resolv.conf
    line: "nameserver 8.8.8.8"
    state: present
  become: true

- name: Add secondary DNS
  lineinfile:
    path: /etc/resolv.conf
    line: "nameserver 8.8.4.4"
    state: present
  become: true