---
- name: Configure Cloudflare WARP
  hosts: all
  become: true
  vars:
    # Example: override via CLI -e warp_license_key=XXXX-XXXX-XXXX-XXXX
    warp_license_key: ""
    warp_mode: "warp+doh"
    warp_excluded_hosts:
      - region1.v2.argotunnel.com
      - region2.v2.argotunnel.com
      - "{{ garage_api_server_name }}"
  roles:
    - role: yamisskey.servers.cloudflare_warp
      tags: [cloudflare, warp]
