- name: Ensure backup directory exists
  file:
    path: /misskey-data/backups
    state: directory
    owner: '{{ ansible_user }}'
    group: '{{ ansible_user }}'
    mode: '0755'

- name: Ensure misskey-backup directory exists
  file:
    path: /opt/misskey-backup
    state: directory
    owner: '{{ ansible_user }}'
    group: '{{ ansible_user }}'
    mode: '0755'

- name: Copy Dockerfile to target
  copy:
    src: '{{ backup_script_dir }}/Dockerfile'
    dest: /opt/misskey-backup/Dockerfile
  notify:
    - Restart backup container

- name: Copy docker-compose.yaml to target
  copy:
    src: '{{ backup_script_dir }}/compose.yaml'
    dest: /opt/misskey-backup/docker-compose.yaml
  notify:
    - Restart backup container

- name: Ensure config directory exists
  file:
    path: /opt/misskey-backup/config
    state: directory
    owner: '{{ ansible_user }}'
    group: '{{ ansible_user }}'
    mode: '0755'

- name: Copy .env file to target
  copy:
    src: '{{ backup_script_dir }}/.env'
    dest: /opt/misskey-backup/config/.env
  notify:
    - Restart backup container

- name: Load environment variables from .env file
  shell: |
    set -o allexport
    source /opt/misskey-backup/config/.env
    set +o allexport
  args:
    executable: /bin/bash

- name: Create rclone config file
  template:
    src: '{{ set_dir }}/ansible/playbooks/templates/rclone.conf.j2'
    dest: /opt/misskey-backup/config/rclone.conf
  notify:
    - Restart backup container

- name: Pull and build Docker images
  docker_compose:
    project_src: /opt/misskey-backup
    state: present
    pull: yes
    build: yes

- name: Start Docker Compose services
  docker_compose:
    project_src: /opt/misskey-backup
    state: started
    restarted: yes
