- name: Create backup directory structure
  file:
    path: "{{ item }}"
    state: directory
    owner: '{{ ansible_user }}'
    group: '{{ ansible_user }}'
    mode: '0755'
  loop:
    - "{{ backup_dir }}/misskey"
    - "/opt/misskey-backup"
    - "/opt/misskey-backup/config"
    - "/opt/misskey-backup/src"
    - "/opt/misskey-backup/backups"

- name: Clone misskey-backup repository
  git:
    repo: "https://github.com/yamisskey-dev/yamisskey-backup.git"
    dest: "/opt/misskey-backup"
    version: "main"
    force: yes
  register: git_clone

- name: Create rclone config file
  template:
    src: templates/rclone.conf.j2
    dest: /opt/misskey-backup/config/rclone.conf
    mode: '0644'
  notify: Restart backup container

- name: Check if backup service is already running
  docker_container_info:
    name: backup
  register: backup_container

- name: Pull and build Docker images
  community.docker.docker_compose_v2:
    project_src: /opt/misskey-backup
    state: present
    pull: yes
    build: yes
  when: not backup_container.exists or backup_container.container.State.Status != 'running'
  register: compose_pull_build

- name: Start Docker Compose services
  community.docker.docker_compose_v2:
    project_src: /opt/misskey-backup
    state: present
  when: not backup_container.exists or backup_container.container.State.Status != 'running'
  register: compose_start

- name: Run manual backup script
  command: sudo docker exec misskey-backup /root/backup.sh

- name: Load secrets from secrets.yml
  include_vars:
    file: '{{ misskey_backup_secrets_file }}'