- name: Ensure backup directory exists
  file:
    path: /misskey-data/backups
    state: directory
    owner: '{{ ansible_user }}'
    group: '{{ ansible_user }}'
    mode: '0755'

- name: Ensure misskey-backup directory exists
  file:
    path: /opt/misskey-backup
    state: directory
    owner: '{{ ansible_user }}'
    group: '{{ ansible_user }}'
    mode: '0755'

- name: Copy Dockerfile to target
  copy:
    src: ~/misskey-backup/Dockerfile
    dest: /opt/misskey-backup/Dockerfile
  notify:
    - Restart backup container

- name: Copy docker-compose.yaml to target
  copy:
    src: ~/misskey-backup/compose.yaml
    dest: /opt/misskey-backup/docker-compose.yaml
  notify:
    - Restart backup container

- name: Pull and build Docker images
  docker_compose:
    project_src: /opt/misskey-backup
    state: present
    pull: yes
    build: yes

- name: Start Docker Compose services
  docker_compose:
    project_src: /opt/misskey-backup
    state: started
    restarted: yes
