---
# Minecraft Server Handlers

- name: restart minecraft server
  block:
    - name: Stop and remove existing containers
      community.docker.docker_compose:
        project_src: '{{ minecraft_dir }}'
        state: absent
      ignore_errors: yes
    
    - name: Start minecraft server
      community.docker.docker_compose:
        project_src: '{{ minecraft_dir }}'
        state: present
        pull: yes
  listen: "restart minecraft"

- name: reload systemd
  systemd:
    daemon_reload: yes
  become: true

- name: restart playit service
  systemd:
    name: playit
    state: restarted
    enabled: yes
  become: true
  listen: "restart playit"